### ISSUE TITLE
Available attributes should be independent of localization

### ISSUE THREAD

**Issue by Taxuspt** [joke2k/faker#1014]
* Faker version: 2.0.3
* OS: OS X

When using localization, the available methods should be the same as the default localization.

### Steps to reproduce

```
In [1]: import faker

In [2]: fake = faker.Factory.create()

In [3]: fake.zipcode()
Out[3]: '51961'

In [4]: fake = faker.Factory.create('fr-FR')

In [5]: fake.zipcode()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-cd7503975a92> in <module>
----> 1 fake.zipcode()

AttributeError: 'Generator' object has no attribute 'zipcode'
```

### Expected behavior

If a certain localization doesn't have an attribute that exists on the default then it should revert to the default localization.

**Comment by djunehor** [comment]
I agree with this suggestion. Providers (available methods) should be independent of locale. So, if I do something like:
```
fake = Fake('en_NG')
fake.vat()
```

If there's no vat method specific to en_NG locale, it should use the default vat() method instead of breaking. That makes the package more efficient and I think it's how faker package in other languages are structured.


Let's have a list of providers: person, date, phone, internet etc.
Then each locale extends the default provider methods. It's a breaking change, so I'll suggest it should be a major release

**Comment by fcurella** [comment]
The reason not all providers have a `vat` method is that not all countries have VAT.

Another issue with what you suggest is in defining what should the "default" `vat` method.

**Comment by djunehor** [comment]
I used VAT as an (inappropriate) example, vat won't be in the list of default providers. Default providers should be details that can be locale independent. Here's a list:
Address
Barcode
Color
Company
DateTime
File
Image
Email
Phone
Name
UserAgent
MobileCarrier


The list is not exhaustive, but those are details that are locale independent, en_US can be set as default locale.

**Comment by fcurella** [comment]
@djunehor I'm confused. Fallback to `en_US` is already the current behavior.

I think the current behavior is OK, but we need to document which methods are guaranteed to be always available.

Going back to this issue's initial example, `zipcode` is not guaranteed to be in every provider because it's a US-specific implementation (ie: it's spec is defined by the USPS). But all address providers have a `postcode` method that return some kind of 'area identifier'.

**Comment by djunehor** [comment]
Sorry I confused you. Yes, the current behaviour falls back to `en_US`. 

What I'm saying is instead of having to create locale folder in ~22 places [address, automotive, bank etc] as is presently, the package should be structured such that we only have to create e.g `en_NG` locale once. So, the file structure will be like
```
Providers
    --zh_TW
    --uk_UA
    --id_ID
  address.py
  phone.py
  name,py
```

You might want to check this https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider to better understand.

**Comment by fcurella** [comment]
@djunehor The code used to be structured that way, but we changed to be "provider-centric" so that people could extend Faker by writing their own providers.

**Comment by djunehor** [comment]
I didn't meet that era 😊. However, I still think we should find a way to avoid having locale folder in multiple places. Or what do you think?

**Comment by fcurella** [comment]
@djunehor I'm still unclear on what's the problem we're trying to solve. What would the new structure achieve that we currently can't do?

**Comment by djunehor** [comment]
The original problem raised is not an issue as zipcode is peculiar to the US only so the error is appropriate. In other words, there's no problem here we're trying to solve.

**Comment by fcurella** [comment]
@djunehor This would be a big change, and I don't feel like it's worth it.

@Taxuspt I'll leave it up to you close the ticket, or add to the conversation.

**Comment by towr** [comment]
`zipcode()` is literally an alias in the en_US provider for `postcode()` (It adds a bunch of aliases that only work for en_US)
I'm tempted to suggest that aliases should result in a warning to please use the canonical method instead. And perhaps for methods that only exist in a specific locale could an error could mention for which locales they exist (though that's a lot more work).
