### ISSUE TITLE
Python 2.7 EOL plans (Leaving feedback is encouraged)

### ISSUE THREAD

**Issue by malefice** [joke2k/faker#1063]
In a little over a month, the PSF will end support for Python 2. @fcurella, what do you intend to do with this project concerning Python 2 EOL? Do you plan to retain support for a certain duration after the EOL date?

In any case, I can help with making everything Python 3 only, but I think `Faker` should have at least one last "semi-significant", if not significant, release that is Python 2 compatible for the poor souls who are stuck with Python 2. Your thoughts?

**Comment by fcurella** [comment]
Once python 2 is EOL, I would like to tag one last release supporting it
and release a new major one dropping support altogether. People stuck on
2.x can just pin to the last supported version (ie `pip install Faker<4").

I don't see the point into staying py2 compatible any longer than that.
People already had plenty of time to upgrade. If they didn't, it's because
something critical is preventing them from doing it, and prolonging Faker's
upgrade is unlikely to change that.

I appreciate any feedback, I'd like for this to be conversation with
Faker's users.

**Comment by malefice** [comment]
I suggest pinning this issue to maximize visibility. I will change the title as well to solicit feedback from users.

**Comment by maxnordlund** [comment]
A last point release would be nice. In addition I would like to see some sort of deprecation/unsupported warning in that versions README/docs.

I don't think a runtime warning would help though. It would only add insult to injury to those poor souls stuck on 2.x

**Comment by fcurella** [comment]
So far, this is the plan:

1. Once python 2 is EOL, release one last version supporting py2.7
2. Clean up the codebase of py2.7-supporting code (`six` etc.)
3. Release new major version supporting only Python 3.

**Comment by malefice** [comment]
The `faker.utils.datetime_safe` module looks like something that can be totally removed as part of the cleanup. Based on what I have read, this module was created to work around the limitations of `strftime()` when handling dates before 1900. This is no longer the case for the versions of Python 3 `faker` supports. At first glance, other code also does not seem to be using the `datetime_safe` module for that purpose either, at least maybe not anymore.
