### ISSUE TITLE
How to set a field as null?

### ISSUE THREAD

**Issue by christoph-teichmeister** [joke2k/faker#1066]
* Faker version: 2.0.4
* Django_Scrubber version: 0.4.1

I'm using django_scrubber with faker and I'm trying to intentionally "fake" a field with `null`.
I cant find anything similar to setting `null` in the docs and simply writing `my_field = None` doesnt work either.

I am aware, that I could write my own management command to null the fields but before I do that, I want to know if there is something similar faker is already providing?
If not, would it be a good idea to add this?

**Comment by fcurella** [comment]
If I'm understanding correctly, you're trying to scrub some field by setting all of its values to `None`.

I'm unclear on how `Faker` could help with that. I'm not familiar with `django_scrubber`, but this looks like an issue on `django_scrubber`'s side.

**Comment by christoph-teichmeister** [comment]
You understood correctly.
`django_scrubber` merely "uses" fakers functionality as in that it allows me to use fakers providers. So instead of `fake.text()` I can write `scrubbers.Faker('text')` and get the same result - hence my reasoning that I should ask here.

What would you do in faker to null a field?

**Comment by malefice** [comment]
> What would you do in faker to null a field?

As far as I know, there is no way to do that, because it is very application-specific when a nullable field should have a null value, and the value of a nullable field is (usually) indicative of some state defined by your application's business logic.

I am not familiar with `django_scrubber`, but I use `factory_boy` which also uses `Faker` as its backend, and for those purposes, I take advantage of [parameters and traits](https://factoryboy.readthedocs.io/en/latest/introduction.html#altering-a-factory-s-behaviour-parameters-and-traits). Granted, your use case is a little different, since you are replacing potentially sensitive data with fake values rather than generating new ones for testing.

A new provider method that only returns `None` can be added, but anything more complex than that is something out of `Faker`'s scope, and the implementation should be left to users/libraries making the calls. @fcurella your thoughts on this?

**Comment by fcurella** [comment]
I 💯 % agree with what @malefice said:

> As far as I know, there is no way to do that, because it is very application-specific when a nullable field should have a null value, and the value of a nullable field is (usually) indicative of some state defined by your application's business logic.

I think this is something that out of scope for Faker and should be fixed on `django_scrubber`'s side.

**Comment by christoph-teichmeister** [comment]
Thank you for your answers and input! We've [inquired] (https://github.com/RegioHelden/django-scrubber/issues/19) about this at`django_scrubber` and they've implemented a solution

**Comment by malefice** [comment]
It looks like `django_scrubber` created a new `FieldFunc` for creating `None` values. I think this issue can be closed now if there is no outstanding action item.
