### ISSUE TITLE
Faker.random_number raises exception randomly

### ISSUE THREAD

**Issue by bontaurean** [joke2k/faker#1074]
* Faker version: 3.0.0

I advise you to document methods parameters and add some kind of validations.

### Actual behavior
```
>>> fake.random_number(fix_len=True)
44805
>>> fake.random_number(fix_len=True)
9543
>>> fake.random_number(fix_len=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "...site-packages/faker/providers/__init__.py", line 157, in random_number
    pow(10, digits - 1), pow(10, digits) - 1)
  File "/usr/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.7/random.py", line 186, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
```

**Comment by malefice** [comment]
@bontaurean if the docs are insufficient, the next thing you should try is to check the source. It is open source after all, but admittedly, the docs can use some work, and not all methods have docstrings, but this one does.

Anyway, this happens when `random_digit()`returns a 0 in this [line](https://github.com/joke2k/faker/blob/6894660b8f6cfdd73f99fda1d60274ad9e42eb20/faker/providers/__init__.py#L154). Basically, each call to this method has a 10% chance of failing. This should be easy to fix, so it is a good first issue for aspiring contributors. Feel free to submit a PR with a fix and better tests if you wish to take the initiative. I will only tackle this if there are no takers for quite some time.

@fcurella regarding docs, should we take advantage of sphinx's `autodoc`, write docstrings for existing provider methods, and require good docstrings for all provider methods moving forward?

**Comment by fcurella** [comment]
@malefice I"m not sure how hard would it be to integrate `autodoc`, since the providers' docs are already autogenerated by our custom `documentor.py`. But we should look into that.
