### ISSUE TITLE
How to set args of  provider `date_this_moth` using cli?

### ISSUE THREAD

**Issue by NamelessAshone** [joke2k/faker#1078]
* Faker version: faker 2.0.0
* OS: 4.19.85-1-MANJARO

I try to use provider `date_this_moth` with arg `after_today`.
### Steps to reproduce

In the document:
> [fake argument ...]: optional arguments to pass to the fake (e.g. the profile fake takes an optional list of comma separated field names as the first argument)

So, I try:
> faker date_this_month False,True
> faker date_this_month after_today=True
> faker date_this_month --after_today=True
> faker date_this_month --after_today
> faker date_this_month after_today

All these commands are not working.

**Comment by malefice** [comment]
I did some digging, and none of the commands work as intended, because the current implementation only parses the optional arguments as a list of strings as shown [here](https://github.com/joke2k/faker/blob/94b166f1305cf4d9fb3611a92713403b5e64d439/faker/cli.py#L228), and this list is not processed any further and is just passed to the underlying provider method on a FIFO basis as shown [here](https://github.com/joke2k/faker/blob/94b166f1305cf4d9fb3611a92713403b5e64d439/faker/cli.py#L83).

For example, if the terminal command is:

```
faker date_this_month after_today=True before_today=False
```

Under the hood in Python, this will call:

```
date_this_month(before_today='after_today=True', after_today='before_today=False')
```

And not like so as one would expect:

```
date_this_month(before_today=False, after_today=True)
```

To fix this, the provider method argument list must be converted into some format, say `(args, kwargs)`, with the appropriate data type conversions before being passed to the underlying method. It is easier said than done though, because provider methods vary a lot with respect to the expected arguments (value and type). Your thoughts on this @fcurella?

**Comment by fcurella** [comment]
I think we should be using [`Click`](https://click.palletsprojects.com/en/7.x/) to save us a lot of troubles when parsing the CLI options.

**Comment by malefice** [comment]
Interesting, I will take a look at this.

**Comment by W1M0R** [comment]
Any progress on this issue?

**Comment by malefice** [comment]
@W1M0R, give me some time.

![image](https://user-images.githubusercontent.com/7114869/92889932-3fe53f80-f449-11ea-8fa5-e34a22b001fe.png)

**Comment by malefice** [comment]
@fcurella so I pretty much implemented almost everything using `Click` (including multiple locale support) except for the `--include` option (I am still sorting out some issues), and there are some "roadblocks" I encountered. Before all that here are some screenshots!

### Running `--help` without a command: 

![image](https://user-images.githubusercontent.com/7114869/93054809-85e61180-f69c-11ea-960a-470275597b68.png)

### Running `--help` with a specified command

![image](https://user-images.githubusercontent.com/7114869/93056154-9c8d6800-f69e-11ea-832c-67593db7a1a3.png)

### Preview of the implementation in action

![image](https://user-images.githubusercontent.com/7114869/93057500-9dbf9480-f6a0-11ea-8351-ba9eb90dd2bb.png)

### Moving on...

I, being biased, think that the new implementation is shaping out to be better than the old implementation, but like I said earlier there are some gotchas to consider and some roadblocks that we have to clear out before this will be a successful implementation.

1. You might have noticed that each command uses the corresponding provider method docstrings as its help text. It would really be nice to have all provider methods properly documented since the RTD pages will no longer be the only one to benefit. Maybe we can open and pin a new issue requesting help?

2. Still on docstrings, multiple locale mode will prioritize the docstrings from the first valid locale as the commands' help texts. For example, if the locale used was `en_US,en_PH,it_IT`, for any given command, it will look up the docstrings of the corresponding provider method in that order. The `name` provider is common across the three locales, so `en_US` will take priority even if (hypothetically) the `it_IT` localization has a very different implementation. The `visayas_province` method is exclusive to `en_PH`, so it will use the `en_PH` docstring. I do not know if there is anything else we can improve for this case.

3. For now, multiple locale mode and the `--seed` option will only output partially reproducible results. The results of each individual locale factory will be reproducible, but the random factory selection logic is not controlled by this seed. Further work is required to fix that issue.

4. This is probably the biggest issue with the most implications. `Click` handles argument parsing and type conversion in a very elegant way, but we still have to specify the datatypes of options/arguments in advance. With the current state of the codebase, I do not think it is possible to fix this [issue](https://github.com/joke2k/faker/issues/1078#issuecomment-566418108) even with the new implementation. The provider methods just vary greatly that `inspect.getfullargspec` will not be enough. This is why running `--help` with a specified command will not list down the options that will be expected as arguments by the corresponding provider method.

To further expound, I am already dynamically generating the command list and the commands themselves based on the other options passed, and I can definitely squeeze in the expected options too, but without any form of type hinting that can be queried via introspection, the only other ways I can think of are:

1. To maintain separate "schema/stub" files that include all the information for each provider method
2. Use `ast` and `eval` just like we did for our sphinx autodoc setup.

Obviously, I am hesitant to use `ast` and `eval` for this because of the totally different threat model. Maintaining separate stub files is just an additional burden considering that the documentation itself is not yet complete. I am leaning towards type hinting via annotations, but I would like to hear your thoughts on the matter.

**Comment by fcurella** [comment]
Thank you so much @malefice , impressive work!

On 1:

> It would really be nice to have all provider methods properly documented

It would also be really helpful to have a CI check to enforce them.

On 2:

> Still on docstrings, multiple locale mode will prioritize the docstrings from the valid locales as the commands' help texts.

I would add, if multiple docstrings are available, I would fallback to the first one available as specified by the user on the command line, rather than random. I've considered prioritizing an available locale that matches the user environment's `LOCALE` and `LANG`, but that would make the algorithm more complicated and I worry the resulting behavior will be more obscure to the user.

On 4:

>  we still have to specify the datatypes of options/arguments in advance

I'm in favor of type hints, since our minimum supported version is python 3.7.

**Comment by malefice** [comment]
> It would also be really helpful to have a CI check to enforce them.

I will do this on a separate PR as well writing some basic non-comprehensive docstrings, just so that we will not get bombarded with CI errors.

> I would add, if multiple docstrings are available, I would fallback to the first one available as specified by the user on the command line, rather than random

Already implemented this on my local repository.

> I'm in favor of type hints, since our minimum supported version is python 3.7.

Yeah, I think this should be a separate PR as well. For now, I will just replace the current implementation with a `Click` implementation (with feature parity) and clean up related legacy code (e.g. `faker.documentor`). 

There will be one (maybe minor) breaking change though, and it will involve how the `-i` or `--include` option works. `Click` supports variadic arguments but not variadic options (equivalent to `argparse`'s optional arguments with `nargs='*'` or `nargs='+').

Technically, we can customize how parsing will be done, but based on what I have seen, it involves subclassing `click.Option` and overriding methods that are not mentioned at all in their API documentation. IMO I would treat those as part of their private API, and I rather not make our implementation potentially brittle yet more complicated, since the breaking change is so easy to remedy. In code form, affected users (if there are any) will only need to do this:

```bash
# Current implementation supports this, but Click implementation does not
faker --include path.to.module path.to.module2 path.to.module3 foo

# Command simply needs to be changed to this
faker --include path.to.module --include path.to.module2 --include path.to.module3 foo
```

**Comment by fcurella** [comment]
@malefice I'm ok with the breaking change, as long as we document the path forward for our users.
