### ISSUE TITLE
Enforce unique generated values

### ISSUE THREAD

**Issue by mlevit** [joke2k/faker#1125]
* Faker version: Latest
* OS: Any

I'm wondering if there is a way of forcing Faker to generate unique values always similar to UUID V4? I'd like to utilise Faker for a tokenisation service but this would required each token to be completely unique. i.e., if I generate a name, it has to be unique each and every time I generate it.

Do you think there's a way to accomplish this? Potentially in a similar way UUID V4 does?

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by brad-engel** [comment]
It may be helpful in your case to generate _n_ tokens up front and cycle through those. Although I think the functions here select random items _with replacement_ so the tokens still wouldn't be distinct. I have a use case that only works _without replacement_, and I think if that were added it would solve both of our needs.

**Comment by towr** [comment]
I've used the decorator below to make functions return unique values. However many providers have a limited number of distinct values and you may run into that limit. And this approach is less efficient than if you could just generate unique values (both because I now store every value I've seen, and because I retry up to 100 times)
For example, an efficient way to generate unique first+last names, would be have different co-prime length arrays of first names and last names, and then cycle through them (because the length are co-prime, you won't repeat a combination until you have used all combinations). A downside is that it's not very random.

```
def unique(fun: callable):
    """
    Wrap a function so it only returns unique values by retrying up to 100 times
    If returning a unique value fails, it throws a ValueError

    :param fun: function to be wrapped
    :return: wrapped function
    """
    used = set()

    @wraps(fun)
    def wrapped(*args, **kwargs):
        for try_idx in range(100):
            val = fun(*args, **kwargs)
            if val not in used:
                used.add(val)
                return val
        raise ValueError(f'Could not generate unique value with "{fun}"')

    return wrapped
```
