### ISSUE TITLE
pydict(variable_nb_elements=False) returns dicts with varying number of elements

### ISSUE THREAD

**Issue by lillitm** [joke2k/faker#1131]
* Faker version: 4.0.1
* OS: OS X 10.15.3

pydict with `variable_nb_elements=False` still has varying number of elements.

### Steps to reproduce

```
from faker import Faker

fake = Faker()

nb = 80
for _ in range(30):  # nb is large and the faker function is called 30 times to increase the probability of reproducing the bug.
    fake_dict = fake.pydict(nb_elements=nb, variable_nb_elements=False)
    nb_reality = len(fake_dict)
    if nb_reality != nb:
        print(nb_reality)
```

### Expected behavior

The length of the dictionary should always be `nb`. 

### Actual behavior

It is often shorter as the keys are generated with [`self.generator.words(nb_elements)`](https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L166). If the keys are not unique, the element is dropped.

**Comment by fcurella** [comment]
Thank you for the report @lillitm.

I think the problem is in https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L166:

```python
        return dict(zip(
            self.generator.words(nb_elements),
            self._pyiterable(nb_elements, False, *value_types),
        ))
```

If we'd call `self.generator.words(nb_elements, unique=True)`, the `dict` won't any duplicate keys to drop.

Feel free to submit a PR and I'll be happy to review it :)

**Comment by lillitm** [comment]
Thank you for your response @fcurella and @mstellon for the fix!
