### ISSUE TITLE
'Generator' object has no attribute ...

### ISSUE THREAD

**Issue by fannyhub** [joke2k/faker#1139]
* Faker version: 4.0.1
* OS: ubuntu

a number of providers causes this problem:
zipcode
postalcode
zipcode_plus4
military_ship

### Steps to reproduce

1. f = Faker('pl_PL')
1. f.zipcode()
1. f.postalcode()

### Expected behavior

I was expecting '80-358'

### Actual behavior

AttributeError: 'Generator' object has no attribute 'postalcode'

**Comment by malefice** [comment]
The provider methods you listed are exclusive to the `en_US` address provider. The `pl_PL` provider does not support those methods, so it is actually behaving as expected.

What is wrong, however, is the current documentation that gives that impression as shown in this [page](https://faker.readthedocs.io/en/master/providers/faker.providers.address.html). Because of how the docs are currently generated, the "standard providers" page use `en_US` provider classes instead of the "core" provider classes, and that is why those methods are included even if they should not be.

While I did not mention this specific issue in #1083, this is something I already addressed in my PR #1128 as part of revamping the provider docs. It is still in a WIP, but you can view what methods are available under `pl_PL` [here](https://maleficefakertest.readthedocs.io/en/docs-housekeeping/locales/pl_PL.html#faker-providers-address).
