### ISSUE TITLE
Bug in internal method _safe_random_int

### ISSUE THREAD

**Issue by anentropic** [joke2k/faker#1152]
I guess maybe it is never called in an unsafe way or this would have come up already, but looking at the code for internal method `_safe_random_int` I think there is a potential problem:

https://github.com/joke2k/faker/blob/0b1f3d8cb14ee2ef051685b06589ee5238e4a084/faker/providers/python/__init__.py#L73
```python
    def _safe_random_int(self, min_value, max_value):
        orig_min_value = min_value
        orig_max_value = max_value

        if min_value is None:
            min_value = max_value - self.random_int()
        if max_value is None:
            max_value = min_value + self.random_int()
        if min_value == max_value:
            return self._safe_random_int(orig_min_value, orig_max_value)
        else:
            return self.random_int(min_value, max_value - 1)
```

It appears from this code that both `min_value` and/or `max_value` could be `None`

But if `max_value` is `None` then this will fail with a `TypeError`:
```python
        if min_value is None:
            min_value = max_value - self.random_int()
```

**Comment by towr** [comment]
Looking at purely the function itself, I think the unlimited recursion when min_value == max_value is worse; it leads to a `RecursionError`.
However, this function only seems to be used in one place, and there checks have been done to ensure they're not both None, or otherwise equal. Adding a docstring with some explanation could help make it clear that's a precondition.
