### ISSUE TITLE
Please support weighted choices

### ISSUE THREAD

**Issue by ex-nerd** [joke2k/faker#1183]
Since Python 3.6, [`random.choices`](https://docs.python.org/3/library/random.html#random.choices) has supported passing in weights for the choices, which would allow for more realistic generation of data sets like random languages (#1179).  It would be nice of `fake.random_elements` and its relations could be updated to support this.

Note that this is different than the current dependency `random_elements` has on `OrderedDict` (I wonder if this dependency is still needed for python >= 3.6), which references probability values (relative to `1.0`) not simple weights (relative to other weight values).

**Comment by eumiro** [comment]
As _realistic_ I understand the distribution of values when called multiple times (applicable to a few providers only):
- `last_name`: some last names are more frequent than others
- `date_of_birth`: age distribution, in the population there are more people around 20 than around 80
- `city_name`: more people are from the capital city than from a random village

**Comment by ex-nerd** [comment]
@malefice Ah, the docs/example seemed to suggest that the weights were based on a 1.0 scale.  That will make things easier to work with. If that's the case, I'll just close this and assume the move away from `OrderedDict` can be dealt with in the discussion about removing support for python2 (assuming that the issues with python 3's built-in dicts do not still require it).

But @eumiro is correct.  There are situations where would be helpful if the data being generated matched more with the real world (particularly when modeling data for search engine development).  It could be implemented as an additional flag on the data set, though that starts to get complex if you want to talk about how distributions change based on which locale you're using (e.g. there is a higher percentage of native Chinese speakers in China than in the US).  Cool idea for thought, though.

**Comment by malefice** [comment]
I still do not get what this issue is really about, so here are some remarks based on what was said.

1. You can use `random_elements` and its variants to perform random sampling with/without replacement, and if you use an `OrderedDict` in tandem with any of those functions, sampling will be performed based on those weights. You essentially have the ability to declare your own probability distribution.

2. You can also localize providers. There are generally more males than there are females around the world, and the male to female ratio is much more skewed in some countries VS in the US, so if you want that to be reflected per locale, then declare and use `OrderedDict`'s containing the respective weights for each of the locales.

3. Generally, we do not use localized weights (as much) for many reasons. One reason is that some data sources just do not provide that info. Second reason is some data sources might have that info, but the sources themselves lack authenticity or authority on the matter. Another reason is it can be an application-specific need that does not really warrant it being included in `Faker`.
