### ISSUE TITLE
Webargs email validation failed with Armenian company emails

### ISSUE THREAD

**Issue by mdantonio** [joke2k/faker#1188]
* Faker version: 4.1.0
* OS: Linux/Ubuntu

Brief summary of the issue goes here.

Company emails with hy_AM (Armenian) localization can contain a last_name company that is considered as invalid by Webargs/Marshmallow (email domains can not contain underscores). I verified that {{last_name}} is a token in the company name format (Is that suspicious? Is it a non-replaced token?)

### Steps to reproduce

1) create a Armenian Faker
> fake = Faker('hy_AM')

2) Produce a number of company_email
> fake.company_email()
'tsormotyansyowzanna@karamanowkyan.biz'
> fake.company_email()
'pvazigeghtsyan@last_name.com'

### Expected behavior

Emails should not contain @last_name domains

### Actual behavior

Armenian emails can contain @last_name domains. I tried with other locales and found no issues

**Comment by malefice** [comment]
The `company_email` method depends on `domain_name` which depends on `domain_word` which depends on `company`. There is a localization available for the `company` method under `hy_AM`, and under this localization, one of the formats has a missing `}` character as shown [here](https://github.com/joke2k/faker/blob/53a8b4aa65471791c80b0708a0c2ae8243e9e713/faker/providers/company/hy_AM/__init__.py#L8).

Whenever this format is randomly selected, the `{{last_name}` portion gets rendered as a literal instead of a valid generator token that will call the `last_name` method. Further "ascii-fication" converts this into the literal `last_name` you have observed in the output.

The issue is caused by a minor typo, and the fix is very simple. If you or any aspiring contributor would like to submit a patch, please feel free to do so. I will submit a PR if there are no takers by next week.
