### ISSUE TITLE
Turkish addresses don't seem to be turkish.

### ISSUE THREAD

**Issue by hasansalimkanmaz** [joke2k/faker#1191]
* Faker version: 4.1.0
* OS:Mac OS

Brief summary of the issue goes here.

Turkish addresses don't seem to be turkish.

### Steps to reproduce

<img width="357" alt="image" src="https://user-images.githubusercontent.com/49716619/83339319-025f0b00-a2cd-11ea-98fe-2df3e2fb627b.png">

### Expected behavior

they should be more similar.

### Actual behavior

"East Kanakchester, WA 45459" can't be a turkish address

**Comment by malefice** [comment]
There is no Turkish localization for the `address` provider, so it will default to the `en_US` locale. What you are getting is actually expected behavior as mentioned in [this section of the README](https://github.com/joke2k/faker#localization). Perhaps you would be interested in making the localization.
