### ISSUE TITLE
About repetition rate

### ISSUE THREAD

**Issue by rainzee** [joke2k/faker#1192]
* Faker version:4.1.0
* OS:MacOs
--------------------
I use faker generate email for data to test one of my project, I only generate 20000 email but after i run sort -u in shell, there are 224 duplicate data, The repetition rate up to 1.12%. For this amount of data, this is obviously too high. I want to know whether this is a problem of the algorithm or other problems. Is there a solution?

**Comment by malefice** [comment]
Yes, no, sort of, but not exactly. Different localizations can have different implementations and different datasets of varying sizes, so I cannot tell you exactly why since you did not specify which email method and which locale you used.

What is certain is that combinatorics plus realistic-looking output plus (semi)official data sources will inevitably limit the number of possible combinations and will eventually lead to duplicates. There are only two general solutions to this. One is to increase the diversity in the datasets (more templates, more person names, more domain names), and another is to allow the generation of email addresses that look obviously fake and/or like spam email addresses.

The former is difficult to do, but it ensures realistic-looking output. The latter is a viable option if you do not mind the ugly email addresses, and you can do it on your own using other provider methods.

**Comment by rainzee** [comment]
> Yes, no, sort of, but not exactly. Different localizations can have different implementations and different datasets of varying sizes, so I cannot tell you exactly why since you did not specify which email method and which locale you used.
> 
> What is certain is that combinatorics plus realistic-looking output plus (semi)official data sources will inevitably limit the number of possible combinations and will eventually lead to duplicates. There are only two general solutions to this. One is to increase the diversity in the datasets (more templates, more person names, more domain names), and another is to allow the generation of email addresses that look obviously fake and/or like spam email addresses.
> 
> The former is difficult to do, but it ensures realistic-looking output. The latter is a viable option if you do not mind the ugly email addresses, and you can do it on your own using other provider methods.

So what you mean is that if I want a realistic email address, repetition is inevitable, unless I define more parameters, then if you simply generate an email address, what do you think is the possible upper limit for him?

**Comment by rainzee** [comment]
I just did another experiment, I added two new parameters in free_email_domains, but the repetition rate instead rose to 4%,why, more parameters means more combinations, less Repeat rate?

**Comment by malefice** [comment]
I do not know if it is the language barrier or not, but I did not mention the word "parameter" even once. I said "increasing the diversity of the **datasets**, because like I already mentioned, different localizations can have **different implementations and different datasets of varying sizes**.

> so I cannot tell you exactly why since you did not specify which email method and which locale you used.

So maybe you should do this, since it might be a bug specific to the locale you used. If it is not a bug, at least I may be able to mathematically compute the total number of possible combinations to give you an idea why you are bound to have duplicates.

> I just did another experiment, I added two new parameters in free_email_domains, but the repetition rate instead rose to 4%,why, more parameters means more combinations, less Repeat rate?

Post your code. I would not know if you did it correctly nor would I know what you meant by "parameter" without the code you used.
