### ISSUE TITLE
Registering custom providers in the faker fixture

### ISSUE THREAD

**Issue by slabko** [joke2k/faker#1228]
* Faker version: 4.1.1
* OS: Ubuntu 20.04

This issue is not really a bug, but rather a feature request (or a question if missed the right way to do that)

I have a suite of my own providers, which I would like to add to the `faker` fixture. However, looking around I didn't find any obvious way of doing so.

### Steps to reproduce
  1. Have a custom generator `project.tests.generators.DeviceGenerator` with an `arm_device` function
  2. Create a test where I would like to create an `arm_device` using the `faker` fixture.

For example:
```
def test_arm_device_architectures(faker):
    device = faker.arm_device()
    assert device_instruction_set(device) == 'risc' 
```

### Expected behavior

There should be a clear way to add a custom providers (`DeviceGenerator` in my case) to the `faker` fixture.

### Actual behavior

The documentation mentions creating custom providers and using the `faker` fixture but nothing about making them work together.

### Personal thought

I can create my own fixture with all the providers registered, but that doesn't seem to be the right way since faker is based on the idea of registering localizations and providers and using it straight away without any wrappers.

**Comment by malefice** [comment]
All the `faker` fixture does is return an appropriate and seeded `Faker` object as per your [configuration](https://faker.readthedocs.io/en/master/pytest-fixtures.html), so if you already have an existing test suite with your custom providers, then you just perform the same operations on the object that `faker` fixture returns. So if your custom provider looks something like this:

```python
from faker.providers import BaseProvider

class CustomProvider:
    def custom_provider_method(self):
        #Implementation goes here
```

You do this, but take note that accessing the `add_provider` directly from the object only works on single locale mode.

```python
from yourmodule import CustomProvider

def test_custom_provider(faker):
    faker.add_provider(CustomProvider)
    faker.custom_provider_method()
    # Test logic goes here
```

For an implementation that also supports multiple locale mode (I recommend reading the [docs](https://faker.readthedocs.io/en/master/fakerclass.html#)), you need to call `add_provider` from the internal factories/generators like so:

```python
from yourmodule import CustomProvider

def test_custom_provider(faker):
    for factory in faker.factories:
        factory.add_provider(CustomProvider)
    faker.custom_provider_method()
    # Test logic goes here
```

Now, if all/most of your tests require that custom provider, then it is quite repetitive to have to call `add_provider` for each test, so you can "modify/inherit" the behavior by creating your own fixture. 

```python
@pytest.fixture
def yourfaker(faker)
    for factory in faker.factories:
        factory.add_provider(CustomProvider)    
    return faker
```

And use that fixture in your tests:

```python
def test_custom_provider(yourfaker):
    # Test logic goes here
```

At least to me, this seems more like a familiarity issue rather than a docs issue, so I highly recommend reading the faker docs and familiarizing yourself with the more advanced features of pytest. I may be biased of course since I wrote the pytest plugin, so if you still find the current faker docs still lacking after reading through the whole thing, then please feel free to submit a PR to fill in the gaps I may have missed.

**Comment by slabko** [comment]
Thank you, @malefice, for such detailed clarification. Indeed that was my first thought to use a self-made inherited fixture, but I was confused by the flexibility and the ability to register custom providers. Because of that flexibility, I could not stop thinking that I'm doing something wrong. It seemed that there was a nice and short way of registering providers without creating a separate fixture. I'm not saying, however, that it is required.

I'll create a PR, and if you find it useful, it might help somebody along the way.
