### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: WSGI application 'src.wsgi.application' could not be loaded; Error importing module.

### ISSUE THREAD

**Issue by bandirom** [joke2k/faker#1232]
* Faker version: 4.1.1
* OS: docker image with Django server

Brief summary of the issue goes here.

### Steps to reproduce

1. step 1 docker-compose configuration with requirements.txt file
1. step 2 If I add a Faker to list I get a exception
1. step 3 If I remove Faker from list, everythink are working

### django.core.exceptions.ImproperlyConfigured: WSGI application 'src.wsgi.application' could not be loaded; Error importing module.
![screen1](https://user-images.githubusercontent.com/46032838/89346030-19492180-d6b1-11ea-8689-18fc02a07259.PNG)
![screen2](https://user-images.githubusercontent.com/46032838/89346021-164e3100-d6b1-11ea-8a2b-473aae53359c.PNG)
![screen3](https://user-images.githubusercontent.com/46032838/89346027-1817f480-d6b1-11ea-9fa7-0cda9b4ad502.PNG)
![screen4](https://user-images.githubusercontent.com/46032838/89346025-177f5e00-d6b1-11ea-9173-f475766b56cc.PNG)
![screen5](https://user-images.githubusercontent.com/46032838/89346301-7cd34f00-d6b1-11ea-9e88-6555d7d37b99.PNG)

But when I removed Faker form list, everything work

I think there is a conflict with Silk module, because when I comment the silk middleware, server has been start

 
![screen6](https://user-images.githubusercontent.com/46032838/89346494-cde34300-d6b1-11ea-968a-318aef7ec76f.PNG)

**Comment by malefice** [comment]
It is winning-the-jackpot-unlikely that `Faker` is the cause of your issues, since as far as this library is concerned, it does not make assumptions about the software you are building. It does, however, provide a `pytest` plugin, but it is also irrelevant in this context.

If you take a closer look at your error logs, the `django.core.exceptions.ImproperlyConfigured` error you are getting is caused by an import error inside the silk package. Specifically, the line `from django.db.models.sql import EmptyResultSet` in silk/sql.py. A quick look at `django-silk`'s github page and a little git blame on the offending file will give you [this](https://github.com/jazzband/django-silk/commit/c20c1deec44d700d465d63f4e62b33eb8089412c).
