### ISSUE TITLE
[REQUEST] Hacktoberfest Topic

### ISSUE THREAD

**Issue by iamnotagentleman** [joke2k/faker#1296]
can we add the "hacktoberfest" topic, for the participate hacktoberfest event

details: https://hacktoberfest.digitalocean.com/

**Comment by malefice** [comment]
@fcurella I am for this but with conditions. If we are to participate, I highly suggest that, within the window, we only accept PR's that are actually non-trivial. I checked my stats here, and my average commit size in this repository is around 600+ lines, and my total contribution in terms of number of lines is more or less equal to the repo's number 2 contributor's and is around twice as large as this repo's number 3 to number 7 contributors' combined.

Under the Hacktober fest rules and with the stuff I am tackling, I might not even end up being eligible for this, but someone who just happened to luck out and make 4 "fix typos" PR's will be. Bluntly, it just sends the wrong message, and while I do not mind not getting a shirt, I also do not want to encourage spam and/or low quality PR's that will inevitably pop up because of this event. At the very least, I want aspiring contributors to actually be deserving and work for it.

IMO, at the very least, they should localize a provider or complete the docs for one. It is easy enough to do one considering that in my first PR here (#1034), I localized 9 providers in one go.

**Comment by fcurella** [comment]
While I do appreciate every single contribution (including one-line typo), I don't want hacktoberfest to put more load on the shoulders of the existing contributors.

Considering that typo fixes are usually the first step for new contributors, I think we need to find a balance between welcoming those PRs, and the workload of current contributors.

I think a good starting point is to have a policy requiring contributors to combine multiple typo fixes in a single PR. In other words, if we see anyone submitting multiple PRs that are typo fix, we ask them to combine them into a single one.

@iamnotagentleman I'm not sure how we would add a 'topic'. Can you be more specific about what needs to be done?

**Comment by Tenzer** [comment]
@fcurella It can be done from https://github.com/joke2k/faker in the sidebar on the left hand side, click the cog:
<img width="333" alt="Screenshot 2020-10-05 at 22 27 04" src="https://user-images.githubusercontent.com/68696/95134045-1d99c580-075a-11eb-8555-9d6972e13959.png">
and then the topic can be added from that screen:
<img width="321" alt="Screenshot 2020-10-05 at 22 27 22" src="https://user-images.githubusercontent.com/68696/95134068-27232d80-075a-11eb-8191-6fe5739949cb.png">

Note that they've updated https://hacktoberfest.digitalocean.com/hacktoberfest-update, so it also includes this:

> Individual pull requests can also be directly opted-in to Hacktoberfest with the ‘hacktoberfest-accepted’ label, on any public GitHub repository, without the need for the ‘hacktoberfest’ repository topic.

**Comment by iamnotagentleman** [comment]
Thanks for the answer 👍 @Tenzer

**Comment by iamnotagentleman** [comment]
@fcurella please check the @Tenzer answer

**Comment by malefice** [comment]
> Individual pull requests can also be directly opted-in to Hacktoberfest with the ‘hacktoberfest-accepted’ label,

Nice! I didn't see the updates before I made my post, but this appears to be a much better compromise. We at least maintain some level of control against potential spammers and bad/low quality PR's. With that new info, I am OK with giving (both existing and new) contributors a pass for those "fix typos"/simple PR under the following rules:

1. If the person already made several/non-trivial contributions to the repo in the past, as a means of thanking them, we give them a pass, so the person gets 1 label.
2. If a new contributor also has another good quality non-trivial PR that gets merged during the window, we give them a label for the other. 
3. If a new contributor has several simple PR's, we give them a single label for those simple PR's.
4. Every one can only be granted a label for simple PR's at most once.

**Comment by fcurella** [comment]
I don't have any control over the the repo's topic, that would have to be done by @joke2k .

I've created the label, but I can't give @malefice 's triaging permissions. @joke2k could you do that for me?
