### ISSUE TITLE
test_date_pattern fails on 4.18.0

### ISSUE THREAD

**Issue by ddevault** [joke2k/faker#1333]
* Faker version: 4.18.0
* OS: Alpine Linux

Brief summary of the issue goes here.

```
======================================================================
FAIL: test_date_pattern (tests.providers.test_date_time.TestThTh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sircmpwn/sources/aports/community/py3-faker/src/Faker-4.18.0/tests/providers/test_date_time.py", line 942, in test_date_pattern
    assert date == "Q"
AssertionError

----------------------------------------------------------------------
```

**Comment by fcurella** [comment]
@bact Can you take a look into this?

**Comment by bact** [comment]
Thank you. Will look at this.

**Comment by ddevault** [comment]
This is reproducible on 5.0.0.

**Comment by bact** [comment]
This is due to the difference on how `musl` and `glibc` handle unsupported directive for `strftime`.

For glibc, it will return the character part of the unsupported directive. So "%Q" will be "Q".
For musl, if it is an unsupported directive, it will just return "" (empty string).

I should probably remove that specific test, because the behavior of this unsupported directive handling is actually undefined.

Alternatively, we can try to normalize the output by ourselves - but I think it probably out of the scope.

**Comment by bact** [comment]
#1337 also got proposed to have an Alpine test environment on Travis.

**Comment by ddevault** [comment]
Thanks @bact!
