### ISSUE TITLE
Faker changes data for same seed

### ISSUE THREAD

**Issue by dgajendr** [joke2k/faker#1392]
* Faker version:4.17.1
* OS:mac OS Catalina

Brief summary of the issue goes here.

### Steps to reproduce

1. Initialize faker based on a constant: Faker.seed(int(constant_string))
2. Generate data such as faker.ssn(), faker.first_name() etc
3. 

### Expected behavior

The generated data should never change anytime based on a constant seed.

### Actual behavior

After a period of time, not sure when exactly, the data generated for the particular constant seed changes completely. I noticed this in few date objects, when the day changes. But for other fields, it was constant. But I think change in month triggered the faker data to be changed. Is there a root cause to it?

**Comment by chitopunk** [comment]
@dgajendr have you found a workaround for this?

**Comment by dgajendr** [comment]
@chitopunk No, I am still looking for a solution. Do you know the root cause of this?

**Comment by prescod** [comment]
Your faker version is very old.

Please install the latest and see if this test program breaks for you.

```
import faker

faker.Faker.seed(25)
fake = faker.Faker()

data = fake.ssn(), fake.first_name(), fake.last_name(), faker.VERSION

assert data == ("387-99-0252", "Jason", "Wiggins", "6.6.3"), data
print("Good")
```

**Comment by prescod** [comment]
(actually I don't know for sure that my values will work on your computer so you may need to adjust them)

**Comment by ELC** [comment]
I can confirm the seed configuration is not working if using multiple locales

**Comment by fcurella** [comment]
> Expected behavior
> The generated data should never change anytime based on a constant seed.

This is partially incorrect. The [expected behavior for seeding](https://github.com/joke2k/faker#seeding-the-generator) is that data should be constant within the same version (not _anytime_):

>  Calling the same methods with the same version of faker and seed produces the same results.

Keeping the datasets constant would mean we can't ever update or fix them. In order to find a balance between stability and moving the project forward, what we do is increment the patch version for _every commit_ and keep a detailed [`CHANGELOG`](https://github.com/joke2k/faker/blob/master/CHANGELOG.md).

If you require the data to never change, maybe you could pin `Faker` to a specific patch version?

**Comment by princelySid** [comment]
> I can confirm the seed configuration is not working if using multiple locales

Me too. 
```
from faker import Faker

fake = Faker(["en_GB", "fr_FR", "en_IN"])
Faker.seed(2043)

print(fake.name())
```
Will produce different names each time but if you use only one locale it works.

Current work around:
```
import random
from faker import Faker

random.seed(2043)
fake = Faker(["en_GB", "fr_FR", "en_IN"])
Faker.seed(2043)


print(fake.name())
```
Not sure why, but both **random.seed** and **Faker.seed** need to be there
