### ISSUE TITLE
How to make a provider which is locale aware?

### ISSUE THREAD

**Issue by prescod** [joke2k/faker#1427]
* Faker version: 8.1.0
* OS: All

I cannot infer from the docs how I make a custom Faker provider which supports multiple languages.

**Comment by fcurella** [comment]
Hi @prescod ,

In order to localize a Provider, you'll have to create a Python package containing modules for each of the supported locales, and each locale will have its own Python class. You can take a look at any of our localized provider (eg: [`address`](https://github.com/joke2k/faker/tree/master/faker/providers/address), or [`lorem`](https://github.com/joke2k/faker/tree/master/faker/providers/lorem)) to get an idea of how the structure and subclassing works.

**Comment by javierjuan** [comment]
Hi @fcurella 

I am trying to create a custom provider that behaves the same in all languages. Should I create a module for each language? Is it not possible to create just one module/class for all languages?

And in any case, how should I have to add the custom provider in multiple locale mode? The method `add_provider` throws the following exception:

`NotImplementedError: Proxying calls to add_provider is not implemented in multiple locale mode.`

Thank you very much.
