### ISSUE TITLE
Arabic Issues

### ISSUE THREAD

**Issue by prescod** [joke2k/faker#1470]
* Faker version:8.8.2
* OS: All

Brief summary of the issue goes here.

### Steps to reproduce

Issue 1. Egyptian Arabic has very few providers:

>>> Faker("ar_EG").first_name()
'Johnny'

Issue 2: What is ar_AA ? There is no country code for "AA".

Questions:

Is ar_AA some kind of generic arabic locale?

Should ar_EG inherit from ar_AA?

Should direct instantiation of ar_AA be discouraged?

**Comment by fcurella** [comment]
> What is ar_AA ? There is no country code for "AA".
> Is ar_AA some kind of generic arabic locale?

Correct. It was introduced in https://github.com/joke2k/faker/commit/420ae236d0c1eb63d278778e6e67de52ba77ab4f as a base class for Arabic locales

While there is no Country code for `AA`, `ar_AA` is a valid _locale_ code:

```python
import locale

locale.locale_alias["ar_aa"]
# 'ar_AA.ISO8859-6'
```

> Should ar_EG inherit from ar_AA?

If it's appropriate for the provider (ie: how much code duplication it saves). I don't know enough Arabic languages and locales to be able to make that call.

> Should direct instantiation of ar_AA be discouraged?

I don't think so. It is a valid value for a locale after all.

**Comment by prescod** [comment]
I'm not an Arabic speaker either, but its hard for me to imagine that this:

```
>>> from faker import Faker
>>> Faker("ar_EG").first_name()
'Erica'
```

Is better than whatever we'd get if we inherited from aa_AA.

Or to put it another way: if aa_AA is intended as a base-class for arabic languages, then every arabic language should inherit from it and either override the inappropriate stuff or remove that particular dataset from ar_AA altogether.

What do you think @ahmedaljazzar

**Comment by fcurella** [comment]
@prescod I would think so too. Ideally we'd have someone from Egypt to make a more informed decision than I ever could.

**Comment by ahmedaljazzar** [comment]
@prescod It's been a long time since I've worked with Arabic locales, but here's what I think

> Issue 1. Egyptian Arabic has very few providers:
Faker("ar_EG").first_name()
'Johnny'

That's correct, I only wanted to introduce a minimum functionality that I needed and I left the rest for the community to contribute as needed.

> Issue 2: What is ar_AA ? There is no country code for "AA".
> Is ar_AA some kind of generic arabic locale?

💯I've had the same question when I saw this first, but after some digging I reached out to the following conclusions:
- It's a valid locale also identified by IBM: [here](https://www.ibm.com/docs/en/aix/7.2?topic=globalization-supported-languages-locales)
- For political reasons, some Arabic countries don't have supported locales; like Palestine. These countries should use `aa_AA` instead.
- Every Arab speaks at least two forms of the language:
   -  **Modern Standard Arabic**: is the grammatically correct, standardised Arabic used in writing and most formal speech across the Arab world.
   - **A local dialect** : Differ vastly from country to country – and even town to town – across the Middle East and North Africa.

So in this case `aa_AA` should represent MSA, and `\b(?!aa_AA\b)aa_[A-Z]{2}` should represent dialects.

> Should ar_EG inherit from ar_AA?
I think this is a great idea, all Arabic dialects inherit from MSA, and I don't see why it should be any different here.

Should direct instantiation of ar_AA be discouraged?
As @fcurella said, and for the above reasons I mentioned, I don't think this is a good idea.

I speak fluent Arabic, and I'm happy to help getting Arabic locales in order here.

**Comment by prescod** [comment]
Thanks so much @ahmedaljazzar. I guess the central question is whether there is any "harm" in changing every aa_XX locale from inheriting from aa_AA so that at the very least the names etc. will tend to be Arabic and not English.

Should we just do that?

**Comment by ahmedaljazzar** [comment]
@prescod I second that. I believe all `aa_` locale should inherit from `aa_AA`. Some outliers like license plate number and phone numbers might not apply here, but in general this is a great idea.
