### ISSUE TITLE
BrokenPipeError when interupting cli output

### ISSUE THREAD

**Issue by therefromhere** [joke2k/faker#1482]
* Faker version: 8.10.1
* OS: Ubuntu 20.04

Brief summary of the issue goes here.

Stopping the faker cli produces a BrokenPipeError, which is a bit untidy.

I think this could be fixed by catching the BrokenPipeError as per https://docs.python.org/3/library/signal.html#note-on-sigpipe (via https://stackoverflow.com/a/58517082/8331 ) ?

### Steps to reproduce

In terminal

`faker | head`

### Expected behavior

Command should cleanly output and shut down

### Actual behavior

Output is:

```
$ faker | head

### faker.providers.address

	fake.address()                                                                                                                           # PO Box 4
	                                                                                                                                           Grahaming 924
	                                                                                                                                           2
	fake.bothify(text='## ??', letters='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')                                               # 38 iv
	fake.building_number()                                                                                                                   # 9
	fake.city()                                                                                                                              # Allenneath
	fake.city_prefix()                                                                                                                       # Mount
Traceback (most recent call last):
  File "/home/johnc/.pyenv/versions/3.9.4/bin/faker", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/home/johnc/.pyenv/versions/3.9.4/lib/python3.9/site-packages/faker/cli.py", line 271, in execute_from_command_line
    command.execute()
  File "/home/johnc/.pyenv/versions/3.9.4/lib/python3.9/site-packages/faker/cli.py", line 248, in execute
    print_doc(arguments.fake,
  File "/home/johnc/.pyenv/versions/3.9.4/lib/python3.9/site-packages/faker/cli.py", line 101, in print_doc
    print_provider(doc, provider, fakers, output=output)
  File "/home/johnc/.pyenv/versions/3.9.4/lib/python3.9/site-packages/faker/cli.py", line 47, in print_provider
    print(f"\t{signature:<{margin}}{separator} {line[i * remains:(i + 1) * remains]}", file=output)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by fcurella** [comment]
Thank you for reporting this @therefromhere ! Do you have time to work on a Pull Request?

**Comment by david-xander** [comment]
- Faker version 8.12.1
- Mac OS X

@fcurella I've been replicating this issue... I've found that when you type in terminal `faker name | head` or `faker address | more` there's no broken pipe error. The issue here is when you type just `faker`. In that case the cli.py prints something like this:
![Screenshot 2021-09-13 at 07 24 14](https://user-images.githubusercontent.com/47969361/133028477-1e875b81-debe-437a-823e-bd49411b7b1d.png)

I've patched the problem when there's no argument with: `Please provide a command or type '?' or  'help' for help`. And then with those new commands I've split the execute() method in order to be able to use the method print_help() of the parser itself before calling execute(). The broken pipe error has been fixed as in the [docs](https://docs.python.org/3/library/exceptions.html#BrokenPipeError). But there still going on a problem when the `faker command` is not found like `faker name2` it prints out this:
![Screenshot 2021-09-13 at 07 45 48](https://user-images.githubusercontent.com/47969361/133030216-6f2f5b5b-c682-4e0a-a2d8-b70f9939c74c.png)

I can solve this out but maybe there's too much out of scope of this issue and it'd be better to create another one with this finding.

Let me know what to do. Thank in advanced.

**Comment by fcurella** [comment]
Thank you for looking into it, @david-xander !

I'd rather break this down into separate PRs. Let's get the easy fix merged first, and then we can tackle the bigger issue.
