### ISSUE TITLE
Adding a custom provider causes random_element to ignore specified sampling probabilities

### ISSUE THREAD

**Issue by mchmutov** [joke2k/faker#1500]
* Faker version: 8.11.0
* OS: Debian GNU/Linux 10 (buster)

It appears that adding a custom provider to a fake causes the random_element method to start ignoring specified sampling probabilities and instead do uniform sampling.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/37190799/130263889-469a6462-e295-42e6-92c9-d26ede531948.png)

### Expected behavior

I expected that after adding the provider, `fake.random_element(elements=opts)` would still return 1 approximately 80% of the time, as it did before adding the provider.

### Actual behavior

Instead, after adding the provider, `fake.random_element(elements=opts)` returns 1 approximately 50% of the time.

**Comment by fcurella** [comment]
Thank you for the report!

I'm not sure when I'll what time to look into this. Probably sometime next week. In the meantime, feel free to submit a Pull Request and I'll be happy to review it :)

**Comment by david-xander** [comment]
@fcurella I've been working on the problem and I know now exactly what the issue is about... It has to do with the use_weighting disabled by default by the BaseProvider class, but not by the Factory class in the provider definition. The 2 cases are then:

- The provider created in the Factory class with use_weighting = True. That's the reasson the probability option works as expected.
- The BaseProvider class has the use_weighting = False.

That explains the weird behaviour. And also the hack is that if the custom provider is defined with __use_weighting__= True, everything works as the user expects it to work. But that isn't fixing the problem to any other person without any clue about it.

There are 2 test that doesn't allow to fix the problem without changing their scope:
- test_weighting_disabled_single_choice
- test_weighting_disabled_with_locales

What should I do in this case to help? If you are Ok that work on this issue.

Thank you in advanced

**Comment by fcurella** [comment]
Thank you for looking into this @david-xander !

To give some context, the reason we have `use_weighting` is that when it's set to `False`, we do some optimizations (ie: we skip some computation) in order to make the provider faster.

Setting it as `True` by default would slow down lots of providers. I'm tempted to treat this as a documentation fix, and make sure our docs explain the flag prominently.

**Comment by david-xander** [comment]
Thank you for you reply. Now I understand better the issue. More or less, I knew that there were a reasson, and that clarifies it. The tests talked again :)

Although, in my opinion (and I could be wrong), at least we should raise and **Exception** only in the use case that the **use_weight** is set to **False** by default and you are using the **probabilities option**. As there's no way you can use that option if you're defining a custom provider, except when you explicitly define **_use_weighting_=True** in the custom provider class. I think that the exception will be completely self-explanatory in that case. And that would be better than expect something that you already know that works perfectly everywhere else but there... Not everybody tests the expected probability as @mchmutov. Maybe that is why users have not previously reported the issue.

**Comment by fcurella** [comment]
@david-xander how would you detect if we're using probabilities? Are you thinking about checking for `if isinstance(OrderedDict)`?

**Comment by david-xander** [comment]
It's not that easy because the **test_weighting_disabled_multiple_locales** won't pass as it uses `OrderedDict` as input for the `opts` in the BaseClass if I remember that well. It's solution must be something very simple in the right place. But the two use cases that I've mentioned are clearly this two:

- I want to use an specific faker.provider and I want to use sampling probabilities. Faker should IGNORE the option, according to the tests.
- I want to use a custom provider and I want to use sampling probabilities. That should rise and exception and should be tested within an assert-rise context.

I'd consider the add_provider... I can think of a couple of ways right now to do this but it should be the least invasive. But the best option, before hand I don't know it yet. If you think it's worth it, I can spend time on it and show you something or discuss it here with you.

**Comment by david-xander** [comment]
I've been thinking a bit of it, and all the options that I thoght would be possible to apply are not. So the problem is that defining any weighting when use `weighting = False` should rise a descriptive exception, as the fact that the computation will never be done with the probabilities defined and that maybe faker should be transparent to the user in that case instead of just ignore it (I'm using a lot of test to explain myself here):

```
        if isinstance(elements, OrderedDict) and not use_weighting:
            raise Exception("Custom weighting are not possible if use_weighting is False. You should define your custom class with use_weighting=True. Use it with caution as it could slow down faker.")
        elif isinstance(elements, dict):
            if not hasattr(elements, "_key_cache"):
                elements._key_cache = tuple(elements.keys())
            
            choices = elements._key_cache
            probabilities = tuple(elements.values()) if use_weighting else None
```

As a consequence the 2 previously mentioned tests fail:

FAILED tests/test_proxy.py::TestFakerProxyClass::test_weighting_disabled_single_choice - Exception: Custom weighting are not possible if use_weighting...
FAILED tests/test_proxy.py::TestFakerProxyClass::test_weighting_disabled_multiple_locales - Exception: Custom weighting are not possible if use_weight

They may be changed to catch the assertRaise exception explicitly, as the case that they're testing shouldn't be a case at all, if my approaching is right.

That's all I can think of for now. 
This is just a suggestion.
Let me know if you want me to PR this or to let it go. No problem. You decide what to do, as you know better where faker is going in the future.

**Comment by fcurella** [comment]
I think the underlying issue is that  the default defined in `__use_weighting__` is defined per-provider, when it should really be per-method or per-dataset/options.

I'm wondering if we should define a custom `WeightedElements` class, and check against that:

```python
class WeightedElements(OrderedDict):
    pass


class BaseProvider:
    # BaseProvider.__use_weighting__ goes away, no more ambiguity

    def random_elements(self, elements=('a', 'b', 'c'), length=None, unique=False,
                        use_weighting=None):

        if use_weighting is True and not instance(elements, WeightedElements):
            raise ValueError("You asked for weighted elements on a a set that doesn't have weights.")

```

But the problem with this approach is that we'll have to go through all of the existing providers and update them.

**Comment by david-xander** [comment]
That's what I thouht initially but discarded for invasiveness... But if you consider it OK, I could make the change and PR it. But it should be a fast PR aproval in order to avoid any missaligment with any other PR that affects any of the whole thing that's going to be easily fixed and tested after. Because the probs of this affecting any PR that toucher any provider must be taking into account. 

Or if you want to do the big picture and you prefer me to test if it would work first... let me know.
