### ISSUE TITLE
bic generation logic (ru_RU)

### ISSUE THREAD

**Issue by NikolayCherniy** [joke2k/faker#1502]
* Faker version: 8.12 (any)
* OS: OS X (any)

Incorrect [bic generation logic](https://github.com/joke2k/faker/blob/f6d09b596862f59cc125c47217e08fecd3062cef/faker/providers/bank/ru_RU/__init__.py#L125). (bank, ru_RU provider)
[bic length should be exactly 9 digits.](https://ru.wikipedia.org/wiki/Банковский_идентификационный_код)
For the first part of the bic code function takes region code, but this code length could be more than 2.
The region that has more than 2 digits in the code is a part of another region and the first two digits of the smaller region are equal to the bigger region code, and only these 2 digits should be included in bic code.
For example, Khanty-Mansi Autonomous Okrug code is 71100 (or 718 in OKTMO),
Yamalo-Nenets Autonomous Okrug code is 71140 (or 719 in OKTMO)
Both of them are part of Tyumen Oblast with code 71.

### Steps to reproduce

from faker import Faker
fake = Faker("ru_RU")
any(len(fake.bic()) > 9 for _ in range(1000))

### Expected behavior

False

### Actual behavior

True

**Comment by 1oglop1** [comment]
@fcurella I just ran into a similar issue.
I noticed that #647 introduced `IBAN` however issue #643 was also about BIC however I did not find any function that would provide BIC. I came across the SEPA Payment Initiation file XSD showing this where BIC was validated using this `[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}` 

However later on I found on Wikipedia that BIC is not needed since 2016.
