### ISSUE TITLE
Feature request: length kwarg for all providers to limit the number of characters in the output

### ISSUE THREAD

**Issue by raviriley** [joke2k/faker#1506]
* Faker version: Latest
* OS:

Brief summary of the issue goes here.

### Expected behavior

For example, `faker.job(max_length=30)` would behave as normal but produce no output that is longer than 30 characters long.

**Comment by omri374** [comment]
If you have a predefined list of elements, you can overwrite the existing functionality and get Faker to return only elements from your list. These can be achieved using a custom provider or a dynamic provider.

Example:

```python
from faker import Faker
from faker.providers import DynamicProvider

# provide your own list of jobs and filter out those who are longer than a value:
max_length = 8
all_elements = ["professor", "doctor", "judge", "policeman", "policewoman", "fire fighter"]
max_length_elements = [element for element in all_elements if len(element) <= max_length]

max_length_jobs_provider = DynamicProvider(provider_name="job", elements=max_length_elements)

# Add the new provider
fake.add_provider(max_length_jobs_provider)

# Call Faker
fake.job()
```
'doctor'


Doing this across the board would either be inefficient (Faker would have to keep sampling until it finds an element of size < X) or very complex (as Faker creates elements based on other elements. E.g. to return a person's name, Faker, with some probability, would sample a first name + a last name. Adding the `max_length` to each provider would result in a first and last name each having max 8 chars, but the full name having max 17 (first + space + last). This can be taken care of but would probably require a significant amount of work.

Hope this helps!

**Comment by ffeldhaus** [comment]
Having the ability to restrict the length of the output for all providers is an important feature for many tests where the input also requires a specific length or where edge cases should be tested.

In my opinion all providers should have the ability to specify `max_length` and `min_length`.

I understand that this is a difficult problem and in my opinion a workaround to create samples until I have one with the right size is not a good solution to the problem. That's why I rather have a proper solution for this important problem directly in Faker than trying to create a workaround for all providers by sampling the output.

**Comment by fcurella** [comment]
I'm definitely open to ideas!
