### ISSUE TITLE
`ElementsType` requires `Sequence[T]`, not just `Iterable[T]`?

### ISSUE THREAD

**Issue by OJFord** [joke2k/faker#1565]
The definition for `ElementsType` currently requires a sequence, or dict keys:

https://github.com/joke2k/faker/blob/7093e5ab9b5e894e04807130b75dc940c7a9d53a/faker/providers/__init__.py#L18

I can't see why it needs to be a _sequence_ though, i.e. having any order - wouldn't `Iterable[T]` suffice?

I hit this by using `random_element(elements)`, where `elements: Set[str]`. I can work around it for now as `random_element(tuple(elements))` of course.

**Comment by fcurella** [comment]
Thank you for the report @OJFord ! Do yu have time to submit a Pull Request?

**Comment by nicarl** [comment]
I had a look and the issue with `Iterable` is that it does not have the magic method `__len__`. However, the code currently relies on the length of `ElementsType`, that is why `Sequence` was chosen instead of `Iterable`.
If you want to use sets `Collection` seems to be the appropriate abstract base class.
`collections` has a very neat table covering this topic: https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes

I think a solution for your problem might be to extend `ElementsType` to:
```
ElementsType = Union[Collection[T], Dict[T, float], KeysView[T], Sequence[T]]
```

PS: I am very happy to see that people use the type annotations :-)

**Comment by OJFord** [comment]
Thanks both - I could certainly submit a PR, but seems a little sneaky now to jump @nicarl on it after he's identified the correct fix. 🙂 

I'd just add that `Sequence` inherits `Collection`, so no need for both. So does `KeysView` (via `Set`) for that matter. `Dict` does too (via `Mapping`, via `MutableMapping`) - but I'm a little fuzzy on whether it's necessary here, it seems to be a `Collection[T]` (its key type) generic over value types. Maybe `ElementsType` can simply be `Collection[T]`.

**Comment by OJFord** [comment]
Ok here's a test:
```python
from typing import Collection
from typing import TypeVar

T = TypeVar("T")
ElementsType = Collection[T]

d = {"test": 1.23}
es: ElementsType[str]

es = d.keys()  # KeysView[T]
es = list(d.keys())  # Sequence[T]
es = d  # Dict[T, float]
```

which passes `mypy --strict` (mypy 0.910).

**Comment by nicarl** [comment]
@OJFord thanks for taking care of this, I was a bit busy the last week. I will have a look at the PR :eyes:
