### ISSUE TITLE
pydecimal provider with positive=True sometimes returns zero

### ISSUE THREAD

**Issue by Tayum** [joke2k/faker#1661]
* `Faker` version: 13.3.4
* OS: Ubuntu 18.04.6

Call `pydecimal` with `positive=True`, and it'll sometimes return a zero.

### Steps to reproduce
Here's an example:
```python
import faker

f = faker.Faker()
are_zero = [f.pydecimal(positive=True, right_digits=0) == 0 for _ in range(1000)]
print(any(are_zero))
```

### Expected behavior

It should always print `False`.

### Actual behavior
Sometimes it's `True` with `f.pydecimal()` returning zero.

**Comment by jhbuhrman** [comment]
In an attempt to solve this issue, we've looked into the implementation. Our conclusion is that this doesn't seem to be a bug, and that `positive=True` should be interpreted as "make it a non-negative number". This happens at [these lines](https://github.com/joke2k/faker/blob/827eea82685fde9377c2e4ba28dc0df7d3bf32f0/faker/providers/python/__init__.py#L222-L225).

It seems more a matter of the documentation describing the correct behavior.

**Comment by Tayum** [comment]
Hey @jhbuhrman, IMO, "positive" and "non-negative" are actually two different terms which differ exactly for a reason that non-negative includes zero as well :)

In a similar [issue](https://github.com/joke2k/faker/issues/1387) for `pydecimal`, this was fixed so not to produce zero value. Please keep that in mind while picking a solution to the issue.

Moreover, if you'll specify `min_value=Decimal('0')` and `positive=True`, you'll still receive the error because of [this check](https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L194-L195). For me it still seems like a bug rather than a documentation issue. :thinking:

**Comment by Tayum** [comment]
@fcurella, I could suggest using: `Decimal('0').next_plus()` (which results in `Decimal('1E-1000026')`)

**Comment by jhbuhrman** [comment]
The [Dutch Wikipedia states](https://nl-m-wikipedia-org.translate.goog/wiki/Positief_getal?_x_tr_sl=nl&_x_tr_tl=en&_x_tr_hl=nl&_x_tr_pto=wapp) that a positive number does _not_ include 0 in the Netherlands, but in Belgium it does. The [English Wikipedia states](https://en.wikipedia.org/wiki/Positive_real_numbers) that 0 is _not_ included. I  mention this to illustrate that the interpretation _can_ be locale-dependent.

I think that we can conclude that:
1. The exact meaning of the `positive` kwarg should be properly documented in the api.
2. Given the comments above, the implementation should be fixed in such a way that 0 is not a valid return value if `positive` is `True`'ish.

**Comment by fcurella** [comment]
@Tayum Thanks, I wasn't aware of `Decimal.next_plus()`.

@jhbuhrman I agree with everything you said. `pydecimal` needs be locale-aware, which means we'll need an additional `python` provider for `nl_BE` and `fr_BE`, at least.

In the docs, we'll also have to mention that the meaning of `positive` is locale-dependent. I don't think most people realize that.
