### ISSUE TITLE
*pyfloat* provider generates the same values for the specific set of parameters.

### ISSUE THREAD

**Issue by VladimirRybalko** [joke2k/faker#1680]
* Faker version: 13.14.0
* OS: Windows 10 Enterprise, x64

Brief summary of the issue goes here.
*pyfloat* method generates the same values for the specific set of parameters.

### Steps to reproduce

```
from faker import Faker

my_min = -1E14
my_max = 1E14
my_precision = 3

faker = Faker()
for _ in range(0, 100)
    print(faker.pyfloat(min_value=my_min , max_value=my_max, right_digits=my_precision))
```

### Expected behavior
Output numbers should be random from the [min, max] range

### Actual behavior
Output contains only two unique values being repeating many times.

**Comment by mochi-moshi** [comment]
You chose a left digit range of 14 with your min and max bounds while specifying 3 right digits, in total making a range of 17 digits. Since you only specified the right digit precision, the provider calculates the left digit precision with `sys.float_info.dig`, with on my Windows 10 Home x64 is 15. This means the calculated min and max values the provider can produce will likely have less digits than the unprocessed random float, which will cap the number at those values.

The idea I'm playing around with to fix it is to use these two lines for the final constraints in _pyfloat_:
`result %= 10**(left_digits-1)`
`result = float((f"%.{right_digits}f") % (result))`
But I'm still fiddling with it.
