### ISSUE TITLE
Address generator keeps generating US based addresses

### ISSUE THREAD

**Issue by gandroz** [joke2k/faker#1762]
* Faker version: 15.3.4
* OS: linux

When using faker to generate fake Canadian based addresses, US based addresses are also generated

### Steps to reproduce

```
from faker import Faker

Faker.seed(0)
fake = Faker(["en_CA", "fr_CA"])
print(fake.address())
```

### Expected behavior

Should return a valid canadian address

### Actual behavior

Returns a US based address
```
48764 Boivin Prairie Apt. 824
Port Gilbert, RI 33335
```

**Comment by stefan6419846** [comment]
`fr_CA` is not an implemented language for the address provider: https://github.com/joke2k/faker/tree/master/faker/providers/address You will see this as well if you turn on debug logging:

```
[...]
2022-12-13 17:30:44 faker.factory._find_provider_class +81: DEBUG    [18846] Looking for locale `fr_CA` in provider `faker.providers.address`.
2022-12-13 17:30:44 faker.factory._find_provider_class +94: DEBUG    [18846] Specified locale `fr_CA` is not available for provider `faker.providers.address`. Locale reset to `en_US` for this provider.
[...]
```

**Comment by gandroz** [comment]
ok, so as "fr_CA" is not implemented the fallback is "en_US" ? That explains why I have US based addresses ?

**Comment by stefan6419846** [comment]
Yes, at the moment every unsupported locale falls back to `DEFAULT_LOCALE`, which is hardcoded to `en_US`: https://github.com/joke2k/faker/blob/7e78eef2565c5ce78b879bf271f520e817f55d4f/faker/factory.py#L85-L95 https://github.com/joke2k/faker/blob/7e78eef2565c5ce78b879bf271f520e817f55d4f/faker/config.py#L5

In your case, *faker* performs a random choice for the locale to use (deciding for `fr_CA`) and generates an address for it, which leads to your address being US-based.

#745 introduced this with the warning logging level, but @fcurella changed this to debug level later on due to a request in #753: https://github.com/joke2k/faker/commit/407932e9bba801f76c607b2b15e2bb1c0ddf5f1a

**Comment by gandroz** [comment]
I understand the previous issues, but my feeling is that logging should have been at a WARNING default level so that every INFO and DEBUG entries would not appear, and this particular log entry should have been a warning at least to inform the end user that its locale is not available. Without this warning, there is no way to be aware of it without digging into the code or changing the logging level, which implies that the user is aware of all of this.
The other way to do is simply to raise an exception as the user tries to access a non-available locale. The fallback to the default locale is to my mind a bad design as it hides an issue in the data provided by the user without letting him be aware of his mistake.

**Comment by stefan6419846** [comment]
Simply changing this to a higher log level or even raising exceptions might conflict with providers which do not have any localization, like the *python*-ones, which only provide the default `en_US` locale as there is nothing to localize. As soon as I decide to use multiple generators for the same *Faker* instance, this could result in such conflicts.
