### ISSUE TITLE
Extract provider logic from provider data?

### ISSUE THREAD

**Issue by jeffwidman** [joke2k/faker#178]
The provider data and provider logic are pretty tightly intertwined. 

It'd be nice if they were separated out--then it'd be a lot easier to port some of the other provider lists out there.

For example, look at how ForgeryPy structures the data separate from the logic--ForgeryPy dictionaries are the equivalent of Faker's Providers: https://github.com/tomekwojcik/ForgeryPy/tree/master/forgery_py/dictionaries

He's got a generic loader that kicks in when a custom function isn't defined for a provider. 

That project seems relatively abandoned, so it'd be nice to pull that clean functionality into this project. 

It'd also probably make it easier for people to localize their providers because they just change the data files without having to think about the attached python code.

**Comment by fcurella** [comment]
see also #181

**Comment by jeffwidman** [comment]
This would probably help with #230, plus I suspect it'd also help with #86 because many of the contributions would be straight flat files rather than code + data. Unfortunately, it's also a lot of work, but I'd be willing to help and sounds like @kissarat would as well

**Comment by malefice** [comment]
@fcurella, as part of the test suite housekeeping process, I was able to get a somewhat good idea of what might be needed to do this, but there are pros and cons depending on how this is implemented. This issue is almost 6 years old, and `Faker` might have been simpler with fewer localized providers back then when this was proposed, but based on what i have seen, ForgeryPy's implementation will probably not be enough.

If we are to use plain and dumb flat files with strictly one item on each row, the only use case we will be able to support will be those simple provider methods that do `random_element(some_list)` like the en_US address provider method ["state"](https://github.com/joke2k/faker/blob/a5cd711ac985eedb4aab704f79907afff44c8bf5/faker/providers/address/en_US/__init__.py#L354).

Slightly more complex use cases like custom probabilities (currently implemented using`OrderedDict`) or provider methods like the en_US provider method ["postcode_in_state"](https://github.com/joke2k/faker/blob/a5cd711ac985eedb4aab704f79907afff44c8bf5/faker/providers/address/en_US/__init__.py#L375) would either require multiple files (a huge pain even for small-ish datasets) or a delimiter-separated file format like a CSV.

Even then, there will still be some weird cases even CSV files cannot cover. One of the things I wanted to do for the PH providers was a `postcode_in_province` method that is very similar to the US provider method `postcode_in_state`, but when I looked into it, coding it was very difficult if limited to the base provider methods or without a list with some custom business logic already baked into it. That is why I settled on postcodes by island group in that case.

So probably what needs to be decided on is the dataset file format(s) that will be accepted into `Faker`. Here are my thoughts:

- Plain dumb flat files with one item per row
  - GOOD: It is just a plain list so it will be easy even for non-programmers to update datasets.
  - BAD: Supported use cases will be restricted to stupid simple as mentioned above.

- Flat files with delimiter separated values (e.g. CSV)
  - GOOD: It essentially functions as a either a flat list or a dict of depth 1 but without being significantly more complicated than the previous option
  - SORT OF BAD: We will probably need to enforce some kind of dialect (like [faker-csv](https://github.com/joke2k/faker/blob/a5cd711ac985eedb4aab704f79907afff44c8bf5/faker/providers/misc/__init__.py#L14)), so that we can handle cases where delimiter characters must be treated as literals instead of delimiters. 
  - BAD: Use cases will still be somewhat limited to what flat lists and dicts can do.

- JSON
  - GOOD and BAD: Arbitrary structure that may contain some business logic that will allow for more complex use cases.
  - GOOD: Every person with some level of programming aptitude/experience probably can handle JSON.
  - BAD: But probably not so friendly towards everybody else.
  - BAD: More prone to syntax and parsing errors
  
- YAML
  - GOOD: Just like JSON without all the quotes and braces, and it feels more semantic and natural a la Markdown.
  - BAD: Requires extra dependency

**Comment by fcurella** [comment]
I'm not too worried about the extra dependency for YAML.

@joke2k also mentioned the possibility of some kind of common format for the different implementations of Faker (ie: PHP, Ruby, etc). I don't want to expand the scope that much, but let's also keep some level of portability in mind.
