### ISSUE TITLE
[Question] generating predictable values

### ISSUE THREAD

**Issue by dvarrazzo** [joke2k/faker#1785]
Hello,

I am considering the integration of Faker with [pg_seldump](https://github.com/dvarrazzo/pg_seldump), a tool I'm developing to create anonymised database dumps - see [issue #7](https://github.com/dvarrazzo/pg_seldump/issues/7).

It would be nice if consecutive dumps could create the same fake data for the same records, so e.g. a first_name would be a function of (table_name: customers, pkey: 12345).

Is there any way to do such a thing, apart from resetting the random number generator to e.g. hash((table_name, pkey)) before generating any value?

Thank you very much!

**Comment by stefan6419846** [comment]
I am not aware of such a mechanism in *faker*. Additionally, I do not think that it actually makes much sense to integrate such a behavior into *faker*, as it is intended for just generating fake data. You can get some sort of deterministic data by using a fixed seed, but this would not serve your use case as well.

Further thinking of this, why should an anonymised database dump show a deterministic behavior regarding the generated values? At least for me, I would not really care much about the actual data and whether it might differs for each dumping process, as long as it has been anonymised. Do you have a real use case where this actually is relevant?

**Comment by dvarrazzo** [comment]
Two minor use cases I have in mind:

1) in case of daily or periodic dump, keep the fake values consistent to provide repeatable tests;
2) in case of denormalized data, give the possibility to create data consistent between the primary and secondary table (so, if for the "customers" table the input value would be `hash(table_name, pkey)`, for the secondary table it would be `hash("customers", fkey)`).

**Comment by fcurella** [comment]
We do have [`.seed` and `.seed_instance`](
https://faker.readthedocs.io/en/master/#seeding-the-generator) which, as
you suggested, you would have to call every time with some kind of
consistent hash.

Something to be aware of is that of the dataset (eg the list of names) is
smaller then your set of hashes, you’re going to get collisions.

I also think this use-case has come up enough times that might be worth it
including it in Faker. But I have no idea what the API could look like, and
nobody has proposed one, yet.

**Comment by StuartMacKay** [comment]
I can throw in a use case for deterministic data - seeding a database with users based on well-known characters. These might be a collection of names "John Smith", "Alice Fernandez", etc. but would be entertaining to add "Homer Simpson", "Moe Szyslak", etc. When writing tests or seeding a database for development it's much easier to generate data for known entities rather than random individuals, particularly if you have an application where you want to build up a specific history of activity.

It's easy to do this by starting with a data structure that contains the desired profiles, so why add this to Faker? The simple reason is packaging and sharing. Providers with known sets of related data are a lot easier to work with, whether that's people or things with a specific profile.
