### ISSUE TITLE
Looking for source for last name data

### ISSUE THREAD

**Issue by coryvisi** [joke2k/faker#1906]
* Faker version: 19.3.1
* OS: MacOSX 13.4

Can the team provide a source for the `last_names` list, similar to how the first name data is described (or point me to somewhere I missed)? Specifically, for the data set in `person/en/__init__.py`, but generally, I think this would be desirable for anyone with licensing concerns (for their data when they generate it).

### Steps to reproduce

1. N/A

### Expected behavior

"Top ### names for the year #### from: http://something"

### Actual behavior

No source found (checked issues, documentation, source code)

**Comment by fcurella** [comment]
I think the list in the `en` provider was creating before we had our [source policy](https://github.com/joke2k/faker/blob/master/docs/coding_style.rst#name-lists) for names. 

Since unsupported locales fall back to `en-US`, I think that list isn't actually ever used on runtime. And we could easily remove it altogether.

**Comment by coryvisi** [comment]
Thank you! I found the locale-specific last_names OrderedDict() and there is a source policy-compliant comment right above it. This solves my immediate problem, although I think removing the source-less fall-back names is a good idea. I'm happy to close the issue if you'd like.
