### ISSUE TITLE
tests/providers/test_ssn.py::TestFiFI::test_ssn_without_age_range - AssertionError: assert '98+' in '010199+953R'

### ISSUE THREAD

**Issue by mgorny** [joke2k/faker#1956]
* Faker version: 20.1.0
* OS: Gentoo Linux amd64 (can reproduce via `tox`)

The following test started failing:

```pytb
============================================================== FAILURES ===============================================================
_________________________________________________ TestFiFI.test_ssn_without_age_range _________________________________________________

self = <tests.providers.test_ssn.TestFiFI testMethod=test_ssn_without_age_range>

    def test_ssn_without_age_range(self):
        current_year = datetime.now().year
        age = current_year - 1995
        ssn = self.fake.ssn(min_age=age, max_age=age, artificial=True)
        assert "95-" in ssn
        age = current_year - 2013
        ssn = self.fake.ssn(min_age=age, max_age=age, artificial=True)
        assert "13A" in ssn
        age = current_year - 1898
        ssn = self.fake.ssn(min_age=age, max_age=age, artificial=True)
>       assert "98+" in ssn
E       AssertionError: assert '98+' in '010199+953R'

tests/providers/test_ssn.py:816: AssertionError
```

Looks like it started failing today (2023-12-02). If I set date to 2023-12-01, it passes again.

### Steps to reproduce

1. `tox -e py311`

**Comment by malefice** [comment]
It has been a while, but hopefully I will be able to contribute to this library somewhat more consistently again.

Anyway, I took a look, and this is happening, because the implementation does not take leap days into account. So what happens is for every leap year that occurs between "today's date" and the target birth year, the "today's date" necessary to spillover to target birth year + 1 gets shifted earlier by one day.  Concrete example, this fails on Dec 2, 2023 for a target year of 1898, because there had been 30 leap days since, and Dec 2, 2023 is 30 days till Jan 1, 2024, and the calculated birth year ends up being Jan 1, 1899 in this date.

It will be transient though, because by the time Jan 1, 2024 hits, the birth years will be correct again, and the test will pass, but it now has the opposite effect where the birth days are late by the number of leap days excluded. In any case, I think the best way to fix this is to make the implementation take into account leap days, and we can also improve the test by freezing time and having a more robust assertion of the generated output (e.g. check the whole ddmmyyc portion of the ssn).
