### ISSUE TITLE
Problem about the new sugession type hint in vs code editor

### ISSUE THREAD

**Issue by RanaUniverse** [joke2k/faker#2040]
Yesterday after the new release of this library i tried to check diffent things, and found this below:::

![image](https://github.com/joke2k/faker/assets/142967497/60c75a87-7c48-4ae1-8763-1f6fbbe73841)

![image](https://github.com/joke2k/faker/assets/142967497/570de58a-c8b8-4e63-804a-6cb3461e1506)

as i got from the sugession i thought i can call the building name parameter without any parameter value and it will return a string, but it is not 😢

See when i get the type hint, i find this and try to get different things checking, but when i did it, 
i found, i got a suggestions as building_name but when i  use it and then run this code in vs code, it shows like this, error, 
so i say is this type of suggestions is wrong here, how to stop this wrong suggestions here, or any mistake i am doing here ?

**Comment by fcurella** [comment]
The issue is that the type stubs are not locale-aware. They pull methods from providers across all locales, even if the instance you're using does not have the `building_name` method.

So let's say the `address` provider for `jp_JP` defines `building_name()`, but the `en_US` doesn't. `building_name()` will be in the suggestions even when you're using `en_US`.

**Comment by parsariyahi** [comment]
For this issue shouldn't we have some exception like 
```python
raise NotImplemented
```
for all `localization` classes
