### ISSUE TITLE
Invalid Zipcodes for US returned

### ISSUE THREAD

**Issue by brizzbane** [joke2k/faker#206]
I'm having an issue w/invalid zipcodes being returned.  I have a database of zipcodes w/lat & longitude, and it would be awesome if valid zipcodes were returned everytime..

**Comment by cabello** [comment]
Please provide examples of invalid US codes, this way you can help the developer to fix that.

**Comment by fcurella** [comment]
Not every combination of digits that makes up zipcode results in a valid zipcode. Zipcodes are pretty much arbitrary numbers associate with geographical boundaries (or, in some cases, companies). 

The only way to just have valid zipcodes would be to choose at random from a list of known valid zipcodes, instead of generating them from an algorithm.

I'm afraid that including such a list of valid zipcodes for each provider may result in a maintenance burden. Zipcodes are constantly added and removed in various country, and we can't possibly keep up with that.

That's one of the reason why my latest efforts are focused on #90 and #178 . With those in place, you could use your own custom provider tailored to your specific needs.
