### ISSUE TITLE
Optional format as string of dates broke existing typed uses

### ISSUE THREAD

**Issue by nils-van-zuijlen** [joke2k/faker#2116]
* Faker version: 30.3.0
* OS: Linux

We have some uses of `date_between` and similar that expect the target variable to be of type `datetime.date`.
The new decorator breaks the type annotations because the output of these functions is now assumed to be `Union[datetime.date, str]`.

### Steps to reproduce

The following code passes type checking in 30.2.0:
```py
foo: datetime.date = Faker().date_between()
```

It does not anymore in 30.3.0:
```
example.py:1: error: Incompatible types in assignment (expression has type "date | str", variable has type "date")  [assignment]
```

### Expected behavior

As the `pattern` argument is `None`, the return type should not have changed.

### Actual behavior

The `pattern` argument is not taken into account to type the return value.

### Possible fix

Using [`typing.overload`](https://docs.python.org/3/library/typing.html#typing.overload) on the affected functions would allow for the return type to be dependent on the parameter types.

This would unfortunately also add quite a lot of repetition to the function definitions, as they need to be repeated multiple times.

**Comment by nils-van-zuijlen** [comment]
Another possible fix would be to only have the decorator on functions that are already returning strings like `date`.

**Comment by nils-van-zuijlen** [comment]
Yes, I am preparing one.

**Comment by Sanchoyzer** [comment]
Hey. I have the same issue. I would like to suggest another solution. Perhaps, it will be better to keep the functions as "clear": `pyint` function will only return `int` type, `uuid4` function will only return `UUID` type, `future_datetime` function will only return `datetime` type, etc; and user will cast it as they want (to string, etc). "Explicit is better than implicit" & "Simple is better than complex"

**Comment by fcurella** [comment]
@Sanchoyzer I'd love to do that, but it would break many people's code.

**Comment by Sanchoyzer** [comment]
@fcurella , version [30.3.0](https://github.com/joke2k/faker/commit/a28c7f6e432af1d6f1ad61e7d8d0d9d00d8a3591#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3)  broke code for anyone using mypy/pylint and date_time providers. It was a minor update (30.2 -> 30.3) instead of the major (30.2 -> 31.0), so this dependency automatically updated => some CI were failed, but but even worse, that some production services were failed.

Ok, let the `uuid4` function be legacy and don't touch it right now, but the `date_time` feature is pretty fresh, so it's possible to undo the wrong solution with minimal effort and do not break the architecture with the "clear" functions.

**Comment by fcurella** [comment]
I've reverted the changes in `30.3.0` and relased `v30.8.2`

**Comment by browniebroke** [comment]
> so this dependency automatically updated => some CI were failed, but but even worse, that some production services were failed.

I understand that it broke type checks so CI makes sense, but I can't see how this was a breaking change for some production services, the values being returned should have a remained the same. Can you give an example please?
