### ISSUE TITLE
Per-Generator random seeding

### ISSUE THREAD

**Issue by akx** [joke2k/faker#349]
(This is an extension of #14 and #259)

So currently, if you do

``` python
f1 = Faker()
f2 = Faker()
f1.seed(123)
```

the `f2` object will effectively be seeded with `123` too due to all of the generators sharing the same `faker.generator.random` `Random()` instance, which is not really optimal.

I would be happy to do the work to fix this (by making the `random` object actually per-`Generator`), if you guys think it's a good idea.

**Comment by fcurella** [comment]
Thanks for pointing this out @akx 

I think it should be per-Generator, since the method is called on the instance. I only worry that some people may be relying on the current (wrong) behaviour.

What would be really awesome would be to have `f1.seed()` and `Faker.seed_module()`, so that anyone relying on the per-module behaviour has a way to fall back.

**Comment by J535D165** [comment]
This would be nice. Very nice actually.

**Comment by reverbc** [comment]
Hi @fcurella, I'm working on this issue as current wrong behavior impacts me, but it occurs to me that in order to make `random` obj per-Generator, we might have to change _**all**_ of the class methods under `Provider` (and its sub-classes) to instance methods so they can benefit from the `self.generator` var set in `BaseProvider` ( https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py#L23 ).

This will be a massive change so I'd like to confirm with you is this the right/intended way to go. Thanks.

**Comment by reverbc** [comment]
Yes the APIs will still be the same with my proposed changes. I did ran the unit tests for ssn module and manually verify the results to make sure it won't break any existing behaviors.

I will send the PR once the work is done. Hopefully not taking too long to reduce the effort of merging other changes.
