### ISSUE TITLE
Specify profile gender

### ISSUE THREAD

**Issue by lukemaxwell** [joke2k/faker#355]
As profile provider names are now gender-specific, it would be great if the class accepted a parameter to allow the user to specify the gender of the profile, e.g profile = fake.profile(sex='M').

Is this within scope? I did a rudimentary test addition to providers/profile/__init__.py, (python 3) -  there was no issue.

**Comment by fcurella** [comment]
That sounds reasonable and trivial to implement, but I'd like to iron out a few issues before going forward.

The first issues I see is that, at least in you description, gender and sex are conflated, which is not a reasonable assumption under some cultures. Since the providers already use 'female' and 'male', I would go with `sex` and be consistent in using `sex`, `female` and `male` throughout code and docs.

Another thing i'm not clear is if the parameter's possible values should be themselves translated to the provider language, eg: should the German provider accept M/F, or M/W? Obviously M/F for everything would be the easiest, but it would be great to have some feedback from non-English users on what _they_ prefer the API to look like.

**Comment by lukemaxwell** [comment]
Thanks fcurella. I only used 'gender' arbitrarily in the issue description, that is confusing.

**Comment by kmike** [comment]
A single set of constants is much better - it enables to switch language without changing source code.

**Comment by fcurella** [comment]
i'm OK with having the arguments `M` or `F` regardless of language. @lukemaxwell could you submit your changes with a Pull Request?

**Comment by navyad** [comment]
That is reasonable enhancement allows flexibility for creating profile. 

@lukemaxwell Have PR is created for this ?  if you are busy, then i can take this up.

**Comment by navyad** [comment]
Hi @fcurella 

I check the source code suggested change is not there, so i have created the MR for that
https://github.com/joke2k/faker/pull/370

**Comment by lukemaxwell** [comment]
Hey sorry I missed this. I'm travelling for the next few weeks so yes - by all means pick up :-) Otherwise I can when I'm back, late August.

L

L

**Comment by navyad** [comment]
@lukemaxwell i have picked up.

**Comment by fcurella** [comment]
closed in #370
