### ISSUE TITLE
Faker generated an invalid email address for nl_NL

### ISSUE THREAD

**Issue by hvdklauw** [joke2k/faker#455]
It generated: chloëbriere@hotmail.com

The ë isn't allowed in the local part according to the spec but it is a valid ascii character so the ascii conversion isn't enough to fix this issue.

**Comment by kungfu71186** [comment]
This issue lies because persons allows for special characters, but there is no localization for nl_NL for emails.

Encoding and Decoding is pretty difficult as well, although python 3 makes it a bit easier. 

It looks like for dutch you can have:
 ä, ë, ï, ö, ü  and possibly acutes Éé	Èè but not sure

We can create a mapping for those at least. Not sure of any others
