### ISSUE TITLE
Fake Part Numbers, Names & Descriptions

### ISSUE THREAD

**Issue by michaelkunc** [joke2k/faker#550]
Is there any interest in adding fake part numbers, names and descriptions? I could see this used for seeding product tables. Examples:
 `fake.part_number()`
`# MHP-17854623`

`fake.part_name()`
`# MOSFET Oscillator`

`fake.part_description()`
`# Electrical Coil Sensor DC Block Type`

I recently had a project where I had to seed a product table, and I'd be happy to do a PR.

**Comment by fcurella** [comment]
I'm not sure about `part_name` and `description`, since they could be already achieved with `words()`. I can see a common enough case for `part_number`, but I don't think there's enough of a common _format_ for it.

I'd rather see the `pystr()` method extended to accept a `format` parameter, so you could call `Faker.pystr(format='???-#####')`
