### ISSUE TITLE
Can `Cornelia Jaceps-Coreth von und zu Coredo und Starkenberg` be deleted from `person/nl_NL`

### ISSUE THREAD

**Issue by robkorv** [joke2k/faker#565]
https://github.com/joke2k/faker/blob/03684c9659c423f689918c0054a923771f097c8f/faker/providers/person/nl_NL/__init__.py#L119 This name is absurdly long and German.... not Dutch.

Would you guys accept a pull request where this one is deleted?

**Comment by vema** [comment]
Hello Robbert,

Interesting question. It  hints to "what is person/nl_NL used for" in
testdata (or what is the purpose of language dependent providers from
faker). Does it represent people living in the Netherlands, born in the
Netherlands, staying in the Netherlands? Or is it purely a collection of
Dutch names?

The testdata I'm using is more of the first category. I'm perfectly happy
to include foreign names in the person category. Examples: 'Maxima
Zorreguieta' or since I'm Belgian 'Doña Fabiola Fernanda
María-de-las-Victorias Antonia Adelaida de Mora y Aragón'

Maybe we need a kind of function that picks a name from a random
pers/xx_XX' provider and only put 'real' names within the providers? Next
question is then of course: what should 'real' dutch names look like? There
are always exceptions (e.g. Lijst_van_Nederlandse_adellijke_families
<https://nl.wikipedia.org/wiki/Lijst_van_Nederlandse_adellijke_families_(naar_titel)>
)

BTW: length is not a criterium for me, My opinion is that it should not be
constrained. If it's too long for your testdata, truncate or don't use it.

Regards,

Marc Verwerft

**Comment by robkorv** [comment]
I expect a realistic test set.

I started this issue because faker was giving me that ridiculous non dutch long name and judging from the other languages they don't have a out off place name like that.

Removing that long name will make it better test set.

**Comment by vema** [comment]
>I expect a realistic test set.
It depends on what you define as realistic. Does this test set represent
people *living* in the Netherlands or is it just a *collection* of Dutch
names?

If e.g., we include family names of Dutch nobles like 'von Hompesch-Rürich
<https://nl.wikipedia.org/wiki/Von_Hompesch-R%C3%BCrich>' or 'de
Preud'homme d'Hailly de Nieuport
<https://nl.wikipedia.org/wiki/De_Preud%27homme_d%27Hailly_de_Nieuport>' is
that OK?

> ... judging from the other languages they don't have a out off place name
like that.
Maybe not, but then again, I can only read/understand a couple of western
languages.

Kind regards,

Marc Verwerft

**Comment by robkorv** [comment]
Can you answer my first question?
I did not expect that I would be the one to judge what this repo considers a good test set. 

I don't want to make that decision, I started this issue to point it out as I'm using it for testing dutch user input and I'm dutch.

When I look at the other languages like:
* https://github.com/joke2k/faker/blob/master/faker/providers/person/ko_KR/__init__.py
* https://github.com/joke2k/faker/blob/master/faker/providers/person/en_TH/__init__.py
* https://github.com/joke2k/faker/blob/master/faker/providers/person/dk_DK/__init__.py

It looks like they use local names.

So let me know if it useful to spend time on a pull request or not.
Tnx for taking the time to respond though :smile:.

----
The most ideal will be an updated list according to some official name database but I'm not gonna do a project like that on company time.

**Comment by fcurella** [comment]
Bearing in mind that the concept of country is fuzzy and doesn't always match the concept of locale (eg: what geographical area exactly is `it_CH`), the datasets are meant to represent a statistaclly realistic set of people living in a Country.

That means that a name shouldn't be included just because someone famous lives there. Ideally, we'd like every list to be from an official governmental statistical office (ie: from a census)

Don't take unsourced providers as a model to follow. Historically, list of names in `Faker` providers were not always based on official statistical data. But we've changed that approach and now we require that every new update must reference some source: https://github.com/joke2k/faker/blob/master/docs/coding_style.rst#data-sets . 

If anybody wants to update the `nl_NL` provider, they will have to get their list from some offical source, and reference that source in the provider.

**Comment by vema** [comment]
The closest I can find for the Netherlands is this site:
http://cbg.nl/bronnen/cbg-familienamen/
It contains approx 320.000 Dutch family names (and Coreth von und zu Coredo
und Starkenberg is not one of them). I'm assuming that data from UWV or
civil registration is not openly available ...

For what it is worth:
- the family name Coreth zu Coredo und Starkenberg
<https://de.wikipedia.org/wiki/Coreth_zu_Coredo_und_Starkenberg> does exist.
- there was already a 'cleanup' action for the Dutch names:
https://github.com/fzaninotto/Faker/commit/a802dded30fa4de56fd442c4436c926a6893f695

Kind regards

**Comment by robkorv** [comment]
Ok, I look into it this weekend. I think these will be a good source:
https://www.svb.nl/int/nl/kindernamen/artikelen/top_3_achternamen/
https://www.svb.nl/int/nl/kindernamen/artikelen/zoeknaam/jongensnamen/jongens_populariteit.jsp
https://www.svb.nl/int/nl/kindernamen/artikelen/zoeknaam/meisjesnamen/meisjes_populariteit.jsp
http://www.cbgfamilienamen.nl/nfb/

**Comment by robkorv** [comment]
I have looked into this. The first names are sort of current.
https://www.svb.nl/int/nl//system/js/kindernamen_jongens.json
https://www.svb.nl/int/nl//system/js/kindernamen_meisjes.json

But the last names I can't check without scraping the whole of http://www.cbgfamilienamen.nl/nfb/.
I'm not gonna do this.
