### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by BLCKPSTV** [joke2k/faker#661]
I'm getting an error using the *args method.

```
fake.email(*args, **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'args' is not defined

```
Also can I change the **kwargs with @gmail to get random@gmail.com?

**Comment by lcd1232** [comment]
@BLCKPSTV just try to call function without arguments: `fake.email()`

**Comment by kungfu71186** [comment]
@BLCKPSTV You don't call it with that in there. Those are there to pass  in arguments. *args would be something like fake.email(1, 2, 'somestring') and kw = keyword, so kwargs would be something like fake.email(domain='gmail.com').

In this case email doesn't have anything like that: https://github.com/joke2k/faker/blob/891e000f06fbc2f13b16331a5577a8d9952281c6/faker/providers/internet/__init__.py#L78

That feature would need to be implemented if you wanted a specific domain. Otherwise, just do what lcd1232 said call it without passing anything in.
