### ISSUE TITLE
TypeError: must be str, not decimal.Decimal with lat & lon

### ISSUE THREAD

**Issue by quintendewilde** [joke2k/faker#686]
I'm getting a weird error when trying to run both lon&lat in a print message: 

`    print("coordinates" + ":" + "[ " + fake.latitude() + "," + fake.longitude() + "] ")
`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not decimal.Decimal
```

**Comment by kungfu71186** [comment]
@BLCKPSTV geo location returns a decimal. You are trying to return print a decimal. You first need to convert to string first.

Also, instead of concatenating like that, try to use formatting instead.
`print("coordinates: [{}, {}]".format(fake.latitude(), fake.longitude()))`

Another note, if you want to find out more of the reason why this occurs, you can read up on type conversion. How to go from one type to another, such as int to string.
