### ISSUE TITLE
Example use to anonymise data

### ISSUE THREAD

**Issue by darrenhaken** [joke2k/faker#778]
Hi,

I would like to use this to anonymise data but maintain referential integrity in the data.
For example, if I have johndoe@gmail.com in two distinct datasets I'd like to be able to join them but anonymise the data.

Is this possible? I would absolutely love some support on this :)

**Comment by kungfu71186** [comment]
Do you have example of what you are trying to do? My interpretation is that you want to randomize the data with expected results? In which case you can use a seed. If that's not what you want, can you clarify a bit?

**Comment by darrenhaken** [comment]
The seed will probably work.

The goal was to store data in a data lake and aninymise PII data but still allow joins. For example if I had a Customer data set and Customers orders dataset that I could join them based on an email address as an identity

**Comment by kungfu71186** [comment]
@darrenhaken are you talking about Factory Boy? http://factoryboy.readthedocs.io/en/latest/
https://github.com/FactoryBoy/factory_boy/

Otherwise you would need to write your own. I had written something similar myself to factory, but it was for oracle db and I wanted the raw sql inserts. I don't think Factory boy can give you the actual raw output. Faker simply randomizes data, it doesn't try to do anything more. You can use factory boy though to create models and randomize your data based off of that and have foreign keys.

**Comment by grrttedwards** [comment]
@darrenhaken 

It sounds like you're looking for the kind of pattern described here:
https://medium.com/district-data-labs/a-practical-guide-to-anonymizing-datasets-with-python-faker-ecf15114c9be

e.g. 

```python
    # Load the faker and its providers
    faker  = Factory.create()
    # Create mappings of names & emails to faked names & emails.
    names  = defaultdict(faker.name)
    emails = defaultdict(faker.email)
    # Iterate over the rows and yield anonymized rows.
    for row in rows:
        # Replace the name and email fields with faked fields.
        row['name']  = names[row['name']]
        row['email'] = emails[row['email']]
        # Yield the row back to the caller
        yield row
```
