### ISSUE TITLE
Unable to generate fake name, email etc.. using faker in python 3.6

### ISSUE THREAD

**Issue by ananthkm1** [joke2k/faker#779]
I am unable to produce fake details(name, email etc..) using Faker package in python 3.6. Installed faker using "Conda install feker"(unable to install via anaconda navigator1.8.7 in win8 )

Installed vscode and spyder

code:
from faker import Faker
fk = Faker()
print(fk.name)

![capture](https://user-images.githubusercontent.com/40577484/42167514-eb77613e-7e2b-11e8-993d-b7f11b0c07bd.PNG)

there is no member like name, email etc..

The following error is displayed:
E1101:Instance of 'Generator' has no 'name' member

**Comment by fcurella** [comment]
@ananthkm1 I'm not well versed in conda, but from what I gather you might need to specify the channel. Would something like `conda install -c anaconda Faker` work?

**Comment by royhananwar** [comment]
@ananthkm1 just type fk.name
IntelliSense from VSCode is not very well
i'm using python 3.6 and VS Code too :)

**Comment by butla** [comment]
@ananthkm1 This is a problem with the dynamic nature of the `Generator` class. It doesn't have these methods, they somehow get added when the object is being created. I had the same issue with Pylint complaining about methods not being there, but I could disable the error in Pylint with the solution from [here](https://stackoverflow.com/a/38976257/2252728). Maybe exceptions like this can be set up for Pycharm's linter?

Anyway, I think you should close the issue, since the name is misleading right now. Or you could rename it, maybe.

**Comment by royhananwar** [comment]
@but

**Comment by fcurella** [comment]
Closing the issue for now. If anyone has a way to make type hints work, a PR will be well accepted :)

**Comment by butla** [comment]
@Meet-Kalariya from what I see you're getting many errors, but they are all pylint (which is a linter, that is "static code analysis") errors. Do you also get errors during execution.

Also, does my explanation from above not work for you?

**Comment by Meet-Kalariya** [comment]
Yes i do get errors during execution
I am not able to understand how to solve this.

**Comment by butla** [comment]
Well, posting the execution error that you're getting could get you along in your quest of solving the problem :-)

**Comment by Meet-Kalariya** [comment]
![image](https://user-images.githubusercontent.com/40663329/51081130-8b909480-170e-11e9-90f6-b207b01971c4.png)

Error
![image](https://user-images.githubusercontent.com/40663329/51081150-0c4f9080-170f-11e9-8547-68dc129ed86e.png)

**Comment by butla** [comment]
Also, pasting the test related to the error, not a bunch of screenshot is a better approach. As you see, Django can't load a setting. So this has nothing to do with Faker. That's first. Second - the error tells you the direct cause of the crash -  what's wrong - Django demands the LOGGING_CONFIG variable set in a config somewhere. I see that you have config loading in your file, but you have a spelling error in `DJANGO_SETTINGS_MODULE` env variable name. And make sure that the module file (`first_project.settings`) exists and has the settings required. You might also wanna start with a working Django template project.

**Comment by Meet-Kalariya** [comment]
Do i have to export DJANGO_SETTINGS_MODULE in my settings.py file?

**Comment by Meet-Kalariya** [comment]
I don't know why but now that file is working and able to fake data but still, there are errors showing

**Comment by itsfk** [comment]
There should be an issue that the module file (first_project.settings) exists and has the settings required

**Comment by MengRS** [comment]
@ananthkm1  A workaround for your particular case (in regards to the linter / faker) - is doing something like `print(fk.format('name')`.  Something like this worked for me - ref doc [here](https://faker.readthedocs.io/en/master/)
Note it states:
> Each call to method fake.name() yields a different (random) result. This is because faker forwards faker.Generator.method_name() calls to faker.Generator.format(method_name)

**Comment by fernandovmacedo** [comment]
I've spent hours trying all sorts of things to "fix" my VS Code autocomplete, thinking it was an intellisense bug on pylance. Just for reference for others searching on Google for a solution for this problem in the future. If your autocomplete is "incomplete" using faker and show "no suggestions" when you type the first letters of the methods, it is because of the dynamic generator class of the package. VS Code is fine. Just live with it, as there's no solution for the problem.
