### ISSUE TITLE
State Abbreviations for en_US have too many

### ISSUE THREAD

**Issue by stephenross** [joke2k/faker#800]
The output of the state provider in address only outputs the 50 states, but the state_abbr has 59 potential outputs

### Steps to reproduce

Generate a value using the state_abbr provider

### Expected behavior

The value should be one of the 50 US states abbreviations

### Actual behavior

The value is one of the 50 US states, Washington DC (DC), American Samoa (AS), Micronesia (FM), Guam (GU), Marshall Islands (MH), Northern Marianas (MP), Palau (PW), Puerto Rico (PR), and Virgin Isles (VI). It appears the list was pulled from sources such as https://www.factmonster.com/us/postal-information/state-abbreviations-and-state-postal-codes that list every possible postal state abbreviation.

**Comment by fcurella** [comment]
Hi @stephenross 

I agree that including US _territories_ in the `state_abbr` is confusing.

The reason they're there is that the purpose of the address provider is to generate valid(ish) postal address, and the USPS uses the territories abbreviation as a postal state abbreviation.

I think we should add an argument to `state_abbr`. Something like `states_only=False`.

The reason I would default it to `False` is because `Faker` is often used for fuzzy testing, and this is a good example of an edge-case people don't usually think of.

**Comment by stephenross** [comment]
Ya, definitely agreed. The reason I bring it up is exactly that, we are using it to do fuzzy testing and the non-state abbreviation caused some of our code to fail.

**Comment by shawnohare** [comment]
I'm not entirely sure I agree. In many contexts the term "state" is used to refer to some subdivision in ISO 3166-2 for a given ISO 3166-1 entity (which need not be the US). 

That being said, as far as I can tell the `state` method looks to only be available for US based address providers, whereas the `region` method is available to some non-US address providers. This tends to imply "state" is US-specific.

I find it more confusing that there isn't simply an `iso3166_{1,2}` method for all address providers.

**Comment by fcurella** [comment]
@shawnohare 

The term 'state' means different things to different people in different contexts (and don't even get me started on 'what _actually_ is a Country?' 😄 ).

In _this_ context, ie: in the context of the 'address provider for US', 'state' is intended as the 'state' part of a postal address - as defined by the USPS in https://pe.usps.com/text/pub28/28apb.htm. If USPS supports a code, so should the provider by default.
