### ISSUE TITLE
wrong language in faker.word() method

### ISSUE THREAD

**Issue by securebean** [joke2k/faker#936]
### Steps to reproduce

1. from faker import Faker 
1. fake = Faker('de_DE')
1. fake.word()

### Expected behavior

Generated word should be in German language

### Actual behavior

Generated word is in Latin. The same situation is with Spanish word() method.

**Comment by fcurella** [comment]
The issue is that the there is no German (or Spanish) localization for the `word` method.

We usually fall back to `en_US` when a localization is missing (https://github.com/joke2k/faker#localization).

The `lorem` provider is a special case in that it falls back to "latin-ish". This is because the original point of the provider was to provide a 'lorem ipsum' kind of text, which one would expect to be in "latin-ish".

I see how this could be confusing from the user perspective. It should at very last fall back to `en_US` as stated in the docs. But switching the fallback locale for `lorem` would be a breaking change.
