### ISSUE TITLE
Faker doesn't obey max_length when used with django + factoryboy

### ISSUE THREAD

**Issue by stuaxo** [joke2k/faker#966]
factory_bot + faker with django is a common use-case.

It would be useful if Fakers() could pick up the max_length of the fields it fakes.

Original bug against FactoryBoy
https://github.com/FactoryBoy/factory_boy/issues/427

**Comment by fcurella** [comment]
`Faker.pystr` already accepts a `max_chars` parameter: https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L17

I'm against the idea of adding a `max_chars` parameter to `word()`, because it would make it occasionally return something that's not a word. Eg `Faker("en-US").word(max_chars=6)` could return `admini`, which is not an English word.

**Comment by stuaxo** [comment]
Does the architecture make it difficult for it to lookup real words in this case?

**Comment by fcurella** [comment]
Not really difficult, but inefficient.

We’ll have to pick words until the length is less or equal than max_chars.
Consider that many users call ‘word()’ inside loops.

 A good way would by to have a list of the words indexes by length, but
indexing in at instantiation time will make instantiation slow. Many user
to instantiation Faker inside a loop in order to generate multi-lingual
values.

**Comment by stuaxo** [comment]
The list could be stored indexed by length, so you have that when you load it.

Or you could have a Trie which is pretty efficent at looking up at words (also - it is much smaller, so less RAM==more speed).

This S/O post has a java-ish implementation of looking up a word in a Trie by length, though they generate an index of word frequencies, which I'm not quite convinced of the value of -

https://stackoverflow.com/questions/46736891/how-to-get-random-words-of-a-give-length-l-from-a-dictionary-which-has-been-im

**Comment by fcurella** [comment]
converting all the lists to somethings else that's also hardcoded will be a
lot of work.

A more practical approach is to convert the list to some other
datastructure, be it a trie or some kind of map, which could happen at
instantiation or at call time.

Whatever we decide to do, I'd like to see some before/after benchmarks.

**Comment by mhoonjeon** [comment]
Any updates on this topic? I'm having the same problem here; my tests break randomly d/t this issue.

**Comment by fcurella** [comment]
Hi @mhoonjeon,

I'm waiting on somebody to submit a PR. Feel free to be the one! :)

**Comment by stuaxo** [comment]
Hi Stale bot,
  This feature would still be a good one to have, if not by default with some other API to say "I want choices to be unique in this scope, globally or globally across all processes.

**Comment by arcanemachine** [comment]
I made a helper function to do this:

```
import factory

from your_app.models import YourModel


def factory_lazy_function(value, max_length=None):
    if max_length is not None:
        max_length = len(value)  # capture entire string by default

    return factory.LazyFunction(lambda: value[:max_length])

# let's use it with a factory...

fake = factory.faker.faker.Faker()

class YourModelFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = YourModel

    phone_number = factory_lazy_function(
        value=fake.phone_number(),
        max_length=YourModel._meta.get_field("phone_number").max_length
    )
```

This function should work even if your model's `max_length` is changed or removed entirely (since it only modifies the length of the string if `max_length` is not `None`... which it will be if you remove the field's `max_length` parameter).

I lack the skill and time to do a proper pull request (for now), so hopefully this will be of use to someone.
